# Generated by Django 3.1.14 on 2022-02-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0004_auto_20220216_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='focusareatag',
            name='blurb',
            field=models.CharField(blank=True, help_text='Used when showing a card linking to this tag', max_length=255),
        ),
        migrations.AddField(
            model_name='sectortag',
            name='blurb',
            field=models.CharField(blank=True, help_text='Used when showing a card linking to this tag', max_length=255),
        ),
    ]
