# Generated by Django 3.2.12 on 2022-03-21 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0012_principletag_principletaggedpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicationtype',
            options={'verbose_name': 'Content type', 'verbose_name_plural': 'Content types'},
        ),
        migrations.AlterModelOptions(
            name='sectortag',
            options={'verbose_name': 'Topic', 'verbose_name_plural': 'Topics'},
        ),
    ]
