[meta]
PROJECT_NAME = "openownership.org"
SHORT_NAME = "openownership"
REPO = "openownership"  # The name of the repo on the remote servers


[envs.remote]
ROOT = "/srv/www/app"

[envs.stage]
HOSTS = ['157.90.26.158', ]
TAG = "staging"
GIT_DEPLOY = "CI"

[envs.prod]
HOSTS = ['167.99.201.240', ]
TAG = "production"
GIT_DEPLOY = "CI"
