[meta]
PROJECT_NAME = "openownership.org"
REPO = "openownership.org"  # The name of the repo on the remote servers

[aws]
REGION = "eu-west-1"
ENDPOINT = "s3-eu-west-1.amazonaws.com"

[envs.remote]
ROOT = "/srv/www/app"

[envs.stage]
HOSTS = ['195.201.99.74', ]
TAG = "staging"
BUCKET = "cdn-openownership.org-staging"
GIT_DEPLOY = "This server can only be deployed with Git. Speak to Andy."

[envs.prod]
HOSTS = ['', ]
TAG = "production"
BUCKET = "cdn-openownership.org-production"
GIT_DEPLOY = "This server can only be deployed with Git. Speak to Andy."
