services:
  # Postgres
  db:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./docker/db/data/:/var/lib/postgresql/data:delegated

  # Redis
  redis:
    restart: always
    image: redis:5.0
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis:/var/lib/redis:delegated
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

  # Application
  web:
    build:
      context: ./app
      cache_from:
        - ghcr.io/hactar-is/openownership:latest
      dockerfile: ../docker/web/Dockerfile
      args:
        - SERVER_ENV=development
        - GITHUB_PUBLIC_KEY=${GITHUB_PUBLIC_KEY}
        - GITHUB_PRIVATE_KEY=${GITHUB_PRIVATE_KEY}
        - PHASE_PROJECT=${PHASE_PROJECT}
        - PHASE_HOST=${PHASE_HOST}
        - PHASE_TOKEN=${PHASE_TOKEN}
    image: ghcr.io/hactar-is/openownership:latest
    environment:
      - SERVER_ENV=development
      - GITHUB_PUBLIC_KEY=${GITHUB_PUBLIC_KEY}
      - GITHUB_PRIVATE_KEY=${GITHUB_PRIVATE_KEY}
      - PHASE_PROJECT=${PHASE_PROJECT}
      - PHASE_HOST=${PHASE_HOST}
      - PHASE_TOKEN=${PHASE_TOKEN}
    restart: always
    volumes:
      - ./app/:/usr/srv/app:cached
      - ./app/media:/usr/srv/app/media:delegated

    ports:
      - "8000:8000"
      - "5000:5000"
    links:
      - db
      - redis
    depends_on:
      - db
      - redis

    command: sleep 1000000
