version: '3.3'

volumes:
  media: {}

services:
  # Postgres
  db:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./docker/db/data/:/var/lib/postgresql/data:delegated

  # Redis
  redis:
    restart: always
    image: redis:5.0
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis:/var/lib/redis:delegated
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

  # Application
  web:
    build:
      context: ./app
      cache_from:
        - ghcr.io/hactar-is/openownership:latest
      dockerfile: ../docker/web/Dockerfile
      args:
        - SERVER_ENV=development
        - ENVKEY=${ENVKEY}
    image: ghcr.io/hactar-is/openownership:latest
    environment:
      - SERVER_ENV=development
      - ENVKEY=${ENVKEY}
      - INDOCKER=1
    restart: always
    volumes:
      - ./app/:/usr/srv/app:cached
      - ./app/media:/usr/srv/app/media:delegated

    ports:
      - "8000:8000"
      - "5000:5000"
    links:
      - db
      - redis
    depends_on:
      - db
      - redis

    command: bash -c "coverage run --source . -m py.test && coverage xml"
