version: '3.3'

services:
  # Postgres
  db:
    image: postgres:10-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./docker/db/data/:/var/lib/postgresql/data:delegated

  # Redis
  redis:
    restart: always
    image: sameersbn/redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis:/var/lib/redis:delegated
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}





  # Application
  web:
    image: TEMPLATEPROJECT_SHORT_NAME:latest
    environment:
      - SERVER_ENV=development
      - ENVKEY=${ENVKEY}
      - INDOCKER=1
    restart: always
    build:
      context: ./app
      dockerfile: ../docker/web/Dockerfile
      args:
        - SERVER_ENV=development
        - ENVKEY=${ENVKEY}
    volumes:
      - ./app/:/usr/srv/app:cached
      - ./app/media:/usr/srv/app/media:delegated

    ports:
      - "8000:8000"
      - "5000:5000"
    links:
      - db
      - redis
    depends_on:
      - db
      - redis

    command: sleep 1000000
