# Generated by Django 3.2.12 on 2022-02-24 15:56

from django.db import migrations, models
import django_extensions.db.fields
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverageScope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
            ],
            options={
                'verbose_name': 'Coverage Scope',
                'verbose_name_plural': 'Coverage Scopes',
            },
        ),
        migrations.RemoveField(
            model_name='disclosureregime',
            name='bulk_data',
        ),
        migrations.RemoveField(
            model_name='disclosureregime',
            name='coverage',
        ),
        migrations.RemoveField(
            model_name='disclosureregime',
            name='r_api',
        ),
        migrations.RemoveField(
            model_name='disclosureregime',
            name='r_central',
        ),
        migrations.AddField(
            model_name='countrytag',
            name='blurb',
            field=models.CharField(blank=True, help_text='Used when showing a card linking to this tag', max_length=255),
        ),
        migrations.AddField(
            model_name='disclosureregime',
            name='api_available',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='API available'),
        ),
        migrations.AddField(
            model_name='disclosureregime',
            name='central_register',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Central Register'),
        ),
        migrations.AddField(
            model_name='disclosureregime',
            name='coverage_legislation_url',
            field=models.URLField(blank=True, null=True, verbose_name='Coverage: Legislation URL'),
        ),
        migrations.AddField(
            model_name='disclosureregime',
            name='data_in_bods',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Data published in BODS'),
        ),
        migrations.AddField(
            model_name='disclosureregime',
            name='definition_legislation_url',
            field=models.URLField(blank=True, null=True, verbose_name='Definition: Legislation URL'),
        ),
        migrations.AddField(
            model_name='disclosureregime',
            name='legislation_url',
            field=models.URLField(blank=True, null=True, verbose_name='Legislation URL'),
        ),
        migrations.AddField(
            model_name='disclosureregime',
            name='public_access_register_url',
            field=models.URLField(blank=True, null=True, verbose_name='Public Access Register URL'),
        ),
        migrations.AddField(
            model_name='disclosureregime',
            name='structured_data',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Structured data'),
        ),
        migrations.AddField(
            model_name='disclosureregime',
            name='year_launched',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Year Launched'),
        ),
        migrations.AddField(
            model_name='disclosureregime',
            name='coverage_scope',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='disclosure_regimes', to='notion.CoverageScope'),
        ),
    ]
