# Generated by Django 3.2.12 on 2022-03-02 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220216_1611'),
        ('notion', '0004_alter_countrytag_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrytag',
            name='map_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.siteimage'),
        ),
    ]
