# Generated by Django 3.2.12 on 2022-03-02 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notion', '0005_countrytag_map_image'),
        ('notion', '0006_alter_countrytag_body'),
    ]

    operations = [
    ]
