# Generated by Django 3.2.12 on 2022-03-02 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0045_auto_20220301_1824'),
        ('notion', '0008_auto_20220302_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrytag',
            name='consultant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultant_countries', to='content.teamprofilepage'),
        ),
    ]
