# Generated by Django 3.2.12 on 2022-03-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notion', '0009_countrytag_consultant'),
    ]

    operations = [
        migrations.AddField(
            model_name='disclosureregime',
            name='stage',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Stage'),
        ),
    ]
