# Generated by Django 3.2.12 on 2022-03-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notion', '0010_disclosureregime_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitment',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Soft deleted'),
        ),
        migrations.AddField(
            model_name='countrytag',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Soft deleted'),
        ),
        migrations.AddField(
            model_name='disclosureregime',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Soft deleted'),
        ),
    ]
