# Generated by Django 3.2.12 on 2022-03-02 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notion', '0011_auto_20220302_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrytag',
            name='regions',
            field=models.ManyToManyField(blank=True, related_name='countries', to='notion.Region'),
        ),
    ]
