# Generated by Django 3.2.12 on 2022-03-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notion', '0012_alter_countrytag_regions'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrytag',
            name='iso2',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ISO2'),
        ),
    ]
