# Generated by Django 3.2.12 on 2022-03-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notion', '0016_alter_countrytag_blurb'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitment',
            name='all_sectors',
            field=models.BooleanField(default=False, verbose_name='All sectors'),
        ),
    ]
