# Generated by Django 3.2.12 on 2022-07-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notion', '0018_auto_20220721_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='disclosureregime',
            name='public_access_legal_basis_url',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Public access: Legal basis URL'),
        ),
        migrations.AddField(
            model_name='disclosureregime',
            name='public_access_protection_regime_url',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Public access: Protection regime URL'),
        ),
        migrations.AddField(
            model_name='disclosureregime',
            name='sanctions_enforcement_legislation_url',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Public access: Legal basis URL'),
        ),
        migrations.AddField(
            model_name='disclosureregime',
            name='sufficient_detail_legislation_url',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Sufficient detail: Legislation URL'),
        ),
        migrations.AlterField(
            model_name='disclosureregime',
            name='coverage_legislation_url',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Coverage: Legislation URL'),
        ),
        migrations.AlterField(
            model_name='disclosureregime',
            name='definition_legislation_url',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Definition: Legislation URL'),
        ),
        migrations.AlterField(
            model_name='disclosureregime',
            name='legislation_url',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Legislation URL'),
        ),
    ]
