# Generated by Django 4.1.5 on 2023-01-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notion', '0020_alter_countrytag_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrytag',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='slug'),
        ),
    ]
