# Generated by Django 4.1.9 on 2023-09-07 11:22

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notion', '0022_countrytag_oo_ongoing_work_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='blurb',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
