# Generated by Django 4.2.4 on 2023-11-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notion', '0024_alter_countrytag_body_alter_countrytag_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commitment',
            name='commitment_type_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Commitment Type'),
        ),
        migrations.AlterField(
            model_name='commitment',
            name='link',
            field=models.URLField(blank=True, default='', max_length=1000, verbose_name='Link'),
        ),
    ]
