# Generated by Django 4.2.4 on 2023-12-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notion', '0025_alter_commitment_commitment_type_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disclosureregime',
            name='bulk_data_available',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Bulk data available'),
        ),
        migrations.AlterField(
            model_name='disclosureregime',
            name='on_oo_register',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='On OO Register'),
        ),
    ]
