# Generated by Django 4.2.4 on 2023-12-08 11:25

from django.db import migrations, models
import django_extensions.db.fields
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notion', '0026_disclosureregime_bulk_data_available_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
            ],
            options={
                'verbose_name': 'Access Tag',
                'verbose_name_plural': 'Access Tags',
            },
        ),
        migrations.AddField(
            model_name='disclosureregime',
            name='who_can_access',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='disclosure_regimes', to='notion.accesstag'),
        ),
    ]
