# Generated by Django 4.2.4 on 2024-08-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notion', '0027_accesstag_disclosureregime_who_can_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='disclosureregime',
            name='responsible_agency',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Responsible agency'),
        ),
    ]
