# Generated by Django 4.2.4 on 2024-08-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notion', '0028_disclosureregime_responsible_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='disclosureregime',
            name='agency_type',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Agency type'),
        ),
    ]
