# Generated by Django 5.2.15 on 2026-06-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notion', '0030_tidy_regime_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disclosureregime',
            name='year_launched',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Launch date'),
        ),
    ]
