# Generated by Django 5.2.15 on 2026-08-10 13:04

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_siteimage_description_alter_sitedocument_file_size'),
        ('notion', '0031_alter_disclosureregime_year_launched'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataUserTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
            ],
            options={
                'verbose_name': 'Data User',
                'verbose_name_plural': 'Data Users',
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImpactTypeTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
            ],
            options={
                'verbose_name': 'Impact Type',
                'verbose_name_plural': 'Impact Types',
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PolicyAreaTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
            ],
            options={
                'verbose_name': 'Policy Area',
                'verbose_name_plural': 'Policy Areas',
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResourceTypeTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
            ],
            options={
                'verbose_name': 'Resource Type',
                'verbose_name_plural': 'Resource Types',
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UsabilityThemeTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
            ],
            options={
                'verbose_name': 'Usability Theme',
                'verbose_name_plural': 'Usability Themes',
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImpactEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notion_id', models.CharField(max_length=255, unique=True, verbose_name='Notion ID')),
                ('notion_created', models.DateTimeField(blank=True, null=True, verbose_name='Notion Created')),
                ('notion_updated', models.DateTimeField(blank=True, null=True, verbose_name='Notion Updated')),
                ('archived', models.BooleanField(blank=True, null=True, verbose_name='Archived')),
                ('deleted', models.BooleanField(default=False, verbose_name='Soft deleted')),
                ('description', models.TextField(default='', verbose_name='Description')),
                ('summary', models.TextField(blank=True, default='', verbose_name='Short summary')),
                ('lessons', models.TextField(blank=True, default='', verbose_name='Lessons')),
                ('oo_outputs_used_in', models.TextField(blank=True, default='', verbose_name='OO outputs used in')),
                ('presentations_used_in', models.TextField(blank=True, default='', verbose_name='Presentations used in')),
                ('source_url', models.URLField(blank=True, default='', max_length=1000, verbose_name='Source URL')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Year')),
                ('publish', models.BooleanField(default=False, verbose_name='Cleared for publication')),
                ('oo_influence', models.BooleanField(default=False, verbose_name='OO influence')),
                ('tangible_impact', models.BooleanField(default=False, verbose_name='Tangible impact')),
                ('international', models.BooleanField(default=False, verbose_name='International')),
                ('source_archived', models.BooleanField(default=False, verbose_name='Archived in Notion')),
                ('source_marked_old', models.BooleanField(default=False, verbose_name='Marked old in Notion')),
                ('archived_types', models.CharField(blank=True, default='', max_length=1000, verbose_name='Archived types')),
                ('countries', models.ManyToManyField(blank=True, related_name='impact_entries', to='notion.countrytag')),
                ('data_users', models.ManyToManyField(blank=True, related_name='impact_entries', to='notion.datausertag')),
                ('regimes', models.ManyToManyField(blank=True, related_name='impact_entries', to='notion.disclosureregime')),
                ('impact_types', models.ManyToManyField(blank=True, related_name='impact_entries', to='notion.impacttypetag')),
                ('policy_areas', models.ManyToManyField(blank=True, related_name='impact_entries', to='notion.policyareatag')),
                ('resource_types', models.ManyToManyField(blank=True, related_name='impact_entries', to='notion.resourcetypetag')),
                ('usability_themes', models.ManyToManyField(blank=True, related_name='impact_entries', to='notion.usabilitythemetag')),
            ],
            options={
                'verbose_name': 'Impact Entry',
                'verbose_name_plural': 'Impact Entries',
                'ordering': ('-year', 'description'),
            },
        ),
        migrations.CreateModel(
            name='ImpactAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort order')),
                ('kind', models.CharField(choices=[('document', 'Document'), ('image', 'Image'), ('link', 'Link')], max_length=20, verbose_name='Kind')),
                ('label', models.CharField(blank=True, default='', max_length=500, verbose_name='Label')),
                ('fingerprint', models.CharField(max_length=1000, verbose_name='Fingerprint')),
                ('url', models.URLField(blank=True, default='', max_length=2000, verbose_name='URL')),
                ('fetch_error', models.TextField(blank=True, default='', verbose_name='Fetch error')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impact_attachments', to='core.sitedocument')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impact_attachments', to='core.siteimage')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='notion.impactentry')),
            ],
            options={
                'verbose_name': 'Impact Attachment',
                'verbose_name_plural': 'Impact Attachments',
                'ordering': ('sort_order', 'pk'),
                'constraints': [models.UniqueConstraint(fields=('entry', 'fingerprint'), name='unique_attachment_per_entry')],
            },
        ),
    ]
