# Generated by Django 5.2.15 on 2026-08-13 13:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notion', '0032_datausertag_impacttypetag_policyareatag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Started')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Finished')),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Succeeded'), ('failures', 'Completed with failures'), ('error', 'Did not finish')], default='running', max_length=20, verbose_name='Status')),
                ('dry_run', models.BooleanField(default=False, verbose_name='Dry run')),
                ('forced', models.BooleanField(default=False, verbose_name='Forced')),
                ('only', models.JSONField(blank=True, default=list, verbose_name='Databases')),
                ('trigger', models.CharField(blank=True, default='', max_length=20, verbose_name='Triggered by')),
                ('fetched', models.PositiveIntegerField(default=0)),
                ('created', models.PositiveIntegerField(default=0)),
                ('updated', models.PositiveIntegerField(default=0)),
                ('skipped', models.PositiveIntegerField(default=0)),
                ('missing_parent', models.PositiveIntegerField(default=0)),
                ('deleted', models.PositiveIntegerField(default=0)),
                ('validated', models.PositiveIntegerField(default=0)),
                ('excluded', models.PositiveIntegerField(default=0)),
                ('invalid_count', models.PositiveIntegerField(default=0)),
                ('missing_column_count', models.PositiveIntegerField(default=0)),
                ('results', models.JSONField(blank=True, default=list)),
                ('error', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Notion sync run',
                'verbose_name_plural': 'Notion sync runs',
                'ordering': ('-started_at',),
                'indexes': [models.Index(fields=['-started_at'], name='notion_sync_started_d62923_idx'), models.Index(fields=['status', '-started_at'], name='notion_sync_status_8517aa_idx')],
            },
        ),
    ]
