# Generated by Django 5.2.15 on 2026-08-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notion', '0034_grant_sync_run_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrytag',
            name='notion_region',
            field=models.CharField(
                blank=True,
                default='',
                max_length=255,
                verbose_name='Region (impact tracker)',
            ),
        ),
    ]
