# Generated by Django 5.2.15 on 2026-08-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notion', '0035_countrytag_notion_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='impactentry',
            name='worldwide',
            field=models.BooleanField(default=False, verbose_name='Global'),
        ),
    ]
