# Generated by Django 5.2.15 on 2026-09-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notion', '0036_impactentry_worldwide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impactentry',
            name='worldwide',
            field=models.BooleanField(
                default=False,
                verbose_name='International (from the countries database)',
            ),
        ),
    ]
