# Generated by Django 3.1.14 on 2022-02-16 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210913_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metatagsettings',
            name='image',
        ),
        migrations.RemoveField(
            model_name='metatagsettings',
            name='site',
        ),
        migrations.RemoveField(
            model_name='navigationsettings',
            name='site',
        ),
        migrations.RemoveField(
            model_name='socialmediasettings',
            name='site',
        ),
        migrations.RemoveField(
            model_name='updatebannersettings',
            name='limit_to_pages',
        ),
        migrations.RemoveField(
            model_name='updatebannersettings',
            name='link_page',
        ),
        migrations.RemoveField(
            model_name='updatebannersettings',
            name='site',
        ),
        migrations.DeleteModel(
            name='AnalyticsSettings',
        ),
        migrations.DeleteModel(
            name='MetaTagSettings',
        ),
        migrations.DeleteModel(
            name='NavigationSettings',
        ),
        migrations.DeleteModel(
            name='SocialMediaSettings',
        ),
        migrations.DeleteModel(
            name='UpdateBannerSettings',
        ),
    ]
