# Generated by Django 3.2.12 on 2022-09-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220216_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteimage',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=40),
        ),
    ]
