# Generated by Django 4.2.4 on 2023-11-30 12:53

from django.db import migrations
import wagtail.images.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_siteimage_file_alter_siteimagerendition_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteimagerendition',
            name='file',
            field=wagtail.images.models.WagtailImageField(height_field='height', storage=wagtail.images.models.get_rendition_storage, upload_to=wagtail.images.models.get_rendition_upload_to, width_field='width'),
        ),
    ]
