# Generated by Django 5.0.10 on 2025-01-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_siteimagerendition_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteimage',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='sitedocument',
            name='file_size',
            field=models.PositiveBigIntegerField(editable=False, null=True),
        ),
    ]
