# Generated by Django 3.1.13 on 2021-09-13 16:02

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilitypage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.siteimage'),
        ),
        migrations.AddField(
            model_name='utilitypage',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.siteimage'),
        ),
        migrations.AddField(
            model_name='searchpagesuggestedsearch',
            name='link_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_for_search', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='searchpagesuggestedsearch',
            name='search_page',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggested_search_items', to='content.searchpage'),
        ),
        migrations.AddField(
            model_name='searchpage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.siteimage'),
        ),
        migrations.AddField(
            model_name='searchpage',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.siteimage'),
        ),
        migrations.AddField(
            model_name='pagefaqlist',
            name='faq_list',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_faq_list', to='content.faqlist'),
        ),
        migrations.AddField(
            model_name='pagefaqlist',
            name='page',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faq_lists', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='newsarticlepage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='news', to='content.NewsCategory'),
        ),
        migrations.AddField(
            model_name='newsarticlepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.siteimage'),
        ),
        migrations.AddField(
            model_name='newsarticlepage',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.siteimage'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.siteimage'),
        ),
        migrations.AddField(
            model_name='indexpagetype',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.siteimage'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.siteimage'),
        ),
        migrations.AddField(
            model_name='featurednewsarticle',
            name='link_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='faqitem',
            name='faq_list',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='content.faqlist', verbose_name='FAQ List'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.siteimage'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.siteimage'),
        ),
        migrations.AddField(
            model_name='featurednewsarticle',
            name='news_index_page',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='featured_articles', to='content.newsindexpage'),
        ),
    ]
