# Generated by Django 3.0.9 on 2020-08-11 14:48

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('core', '0001_initial'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilitypage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.SiteImage'),
        ),
        migrations.AddField(
            model_name='utilitypage',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.SiteImage'),
        ),
        migrations.AddField(
            model_name='searchpagesuggestedsearch',
            name='link_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_for_search', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='searchpagesuggestedsearch',
            name='search_page',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggested_search_items', to='content.SearchPage'),
        ),
        migrations.AddField(
            model_name='searchpage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.SiteImage'),
        ),
        migrations.AddField(
            model_name='searchpage',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.SiteImage'),
        ),
        migrations.AddField(
            model_name='pageheroimage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.SiteImage', verbose_name='Background image'),
        ),
        migrations.AddField(
            model_name='pageheroimage',
            name='page',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero_images', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='pagefaqlist',
            name='faq_list',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_faq_list', to='content.FAQList'),
        ),
        migrations.AddField(
            model_name='pagefaqlist',
            name='page',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faq_lists', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='newsindexpage',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.SiteImage'),
        ),
        migrations.AddField(
            model_name='newsarticlepage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='news', to='content.NewsCategory'),
        ),
        migrations.AddField(
            model_name='newsarticlepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.SiteImage'),
        ),
        migrations.AddField(
            model_name='newsarticlepage',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.SiteImage'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.SiteImage'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.SiteImage'),
        ),
        migrations.AddField(
            model_name='featurednewsarticle',
            name='link_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='featurednewsarticle',
            name='news_index_page',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='featured_articles', to='content.NewsIndexPage'),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.SiteImage'),
        ),
        migrations.AddField(
            model_name='faqitem',
            name='faq_list',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='content.FAQList', verbose_name='FAQ List'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.SiteImage'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.SiteImage'),
        ),
    ]
