# Generated by Django 3.1.14 on 2022-02-02 17:05

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20210913_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_body',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Body text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_headline',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Headline'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='additional_content',
            field=wagtail.fields.StreamField([], blank=True),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='body',
            field=wagtail.fields.StreamField([], blank=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([], blank=True),
        ),
        migrations.AlterField(
            model_name='indexpagetype',
            name='additional_content',
            field=wagtail.fields.StreamField([], blank=True, help_text='The blocks you create here will be displayed below the listing'),
        ),
        migrations.AlterField(
            model_name='indexpagetype',
            name='child_page_stream',
            field=wagtail.fields.StreamField([], blank=True, help_text='The blocks you create here will be displayed below all child pages'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='body',
            field=wagtail.fields.StreamField([], blank=True),
        ),
        migrations.AlterField(
            model_name='newsarticlepage',
            name='additional_content',
            field=wagtail.fields.StreamField([], blank=True),
        ),
        migrations.AlterField(
            model_name='newsarticlepage',
            name='body',
            field=wagtail.fields.StreamField([], blank=True),
        ),
        migrations.AlterField(
            model_name='utilitypage',
            name='additional_content',
            field=wagtail.fields.StreamField([], blank=True),
        ),
        migrations.AlterField(
            model_name='utilitypage',
            name='body',
            field=wagtail.fields.StreamField([], blank=True),
        ),
    ]
