# Generated by Django 3.1.14 on 2022-02-03 13:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0002_auto_20210913_1702'),
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailsearchpromotions', '0002_capitalizeverbose'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('content', '0004_auto_20220203_1216'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IndexSectionPage',
            new_name='SectionListingPage',
        ),
        migrations.AlterModelOptions(
            name='sectionlistingpage',
            options={'verbose_name': 'Section listing page'},
        ),
    ]
