# Generated by Django 3.1.14 on 2022-02-03 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20220203_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepage',
            name='additional_content',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='hero_image',
        ),
        migrations.RemoveField(
            model_name='newsarticlepage',
            name='additional_content',
        ),
        migrations.RemoveField(
            model_name='newsarticlepage',
            name='hero_image',
        ),
        migrations.RemoveField(
            model_name='utilitypage',
            name='additional_content',
        ),
        migrations.RemoveField(
            model_name='utilitypage',
            name='hero_image',
        ),
    ]
