# Generated by Django 3.1.14 on 2022-02-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20220203_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionlistingpage',
            name='show_child_pages',
            field=models.BooleanField(default=True, help_text='Display cards linking to all the child pages'),
        ),
    ]
