# Generated by Django 3.1.14 on 2022-02-03 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210913_1702'),
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('wagtailsearchpromotions', '0002_capitalizeverbose'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('content', '0007_sectionlistingpage_show_child_pages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexpagetype',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='indexpagetype',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='newsarticlepage',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='newsarticlepage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='newsarticlepage',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='newsindexpage',
            name='indexpagetype_ptr',
        ),
        migrations.DeleteModel(
            name='FeaturedNewsArticle',
        ),
        migrations.DeleteModel(
            name='IndexPageType',
        ),
        migrations.DeleteModel(
            name='NewsArticlePage',
        ),
        migrations.DeleteModel(
            name='NewsIndexPage',
        ),
    ]
