# Generated by Django 3.1.14 on 2022-02-08 13:56

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields
import wagtailcache.cache


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210913_1702'),
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('content', '0009_glossarypage'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('blurb', models.TextField(blank=True, null=True)),
                ('display_date', models.DateField(blank=True, help_text='If blank, this will be set to the date the page was first published', null=True)),
                ('headline', models.CharField(help_text='Displayed at the top of the page', max_length=255, null=True)),
                ('additional_content', wagtail.core.fields.StreamField([], blank=True, help_text='The blocks you create here will be displayed below the listing')),
                ('child_page_stream', wagtail.core.fields.StreamField([], blank=True, help_text='The blocks you create here will be displayed below all child pages')),
                ('thumbnail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.siteimage')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtailcache.cache.WagtailCacheMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='JobPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('blurb', models.TextField(blank=True, null=True)),
                ('display_date', models.DateField(blank=True, help_text='If blank, this will be set to the date the page was first published', null=True)),
                ('body', wagtail.core.fields.StreamField([], blank=True)),
                ('application_url', models.URLField(blank=True, help_text='URL of the page where people can apply for the job', max_length=255)),
                ('application_deadline', models.DateField(blank=True)),
                ('thumbnail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.siteimage')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtailcache.cache.WagtailCacheMixin, 'wagtailcore.page'),
        ),
    ]
