# Generated by Django 3.1.14 on 2022-02-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_auto_20220208_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpage',
            name='application_url',
            field=models.URLField(blank=True, help_text='URL of the page where people can apply for the job', max_length=255, verbose_name='Application URL'),
        ),
    ]
