# Generated by Django 3.1.14 on 2022-02-08 17:23

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_add_ctablock_to_article_body_20220208_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobsindexpage',
            name='additional_content',
        ),
        migrations.RemoveField(
            model_name='jobsindexpage',
            name='child_page_stream',
        ),
        migrations.AddField(
            model_name='jobsindexpage',
            name='intro',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
