# Generated by Django 3.1.14 on 2022-02-09 15:38

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_add_authors_to_blog_article_20220209_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticleAuthorRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_articles', to='content.author')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_relationships', to='content.newsarticlepage')),
            ],
            options={
                'verbose_name': 'Article author',
                'verbose_name_plural': 'Article authors',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
