# Generated by Django 3.1.14 on 2022-02-09 18:22

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0022_teamprofilepage_authorship'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamprofilepage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
