# Generated by Django 3.1.14 on 2022-02-10 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0024_publicationauthorrelationship_publicationfrontpage_publicationinnerpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sectionlistingpage',
            options={},
        ),
    ]
