# Generated by Django 3.1.14 on 2022-02-10 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0025_auto_20220210_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicationinnerpage',
            name='sort_order',
        ),
    ]
