# Generated by Django 3.1.14 on 2022-02-15 15:43

from django.db import migrations
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0002_focusareatag_focusareataggedpage'),
        ('content', '0027_add_publication_type_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticlepage',
            name='areas_of_focus',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taxonomy.FocusAreaTaggedPage', to='taxonomy.FocusAreaTag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='jobpage',
            name='areas_of_focus',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taxonomy.FocusAreaTaggedPage', to='taxonomy.FocusAreaTag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='newsarticlepage',
            name='areas_of_focus',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taxonomy.FocusAreaTaggedPage', to='taxonomy.FocusAreaTag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='publicationfrontpage',
            name='areas_of_focus',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taxonomy.FocusAreaTaggedPage', to='taxonomy.FocusAreaTag', verbose_name='Tags'),
        ),
    ]
