# Generated by Django 3.1.14 on 2022-02-15 16:25

from django.db import migrations
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0003_sectortag_sectortaggedpage'),
        ('content', '0028_auto_20220215_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticlepage',
            name='sectors',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taxonomy.SectorTaggedPage', to='taxonomy.SectorTag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='jobpage',
            name='sectors',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taxonomy.SectorTaggedPage', to='taxonomy.SectorTag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='newsarticlepage',
            name='sectors',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taxonomy.SectorTaggedPage', to='taxonomy.SectorTag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='publicationfrontpage',
            name='sectors',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taxonomy.SectorTaggedPage', to='taxonomy.SectorTag', verbose_name='Tags'),
        ),
    ]
