# Generated by Django 3.1.14 on 2022-02-23 11:28

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0029_auto_20220215_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('latest_section_content', wagtail.blocks.StructBlock([('section_page', wagtail.blocks.PageChooserBlock(label='Front page of section', page_type=['content.SectionPage'], required=True))]))], blank=True),
        ),
        migrations.AlterField(
            model_name='sectionpage',
            name='body',
            field=wagtail.fields.StreamField([('latest_section_content', wagtail.blocks.StructBlock([('section_page', wagtail.blocks.PageChooserBlock(label='Front page of section', page_type=['content.SectionPage'], required=True))]))], blank=True),
        ),
    ]
