# Generated by Django 3.2.12 on 2022-02-25 12:31

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import modules.content.blocks.stream
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.search.index
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220216_1611'),
        ('wagtailcore', '0066_collection_management_permissions'),
        ('content', '0034_jobpage_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='PressLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL')),
                ('title', models.CharField(max_length=255)),
                ('blurb', models.CharField(blank=True, max_length=255)),
                ('first_published_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('section_page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Section')),
                ('thumbnail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.siteimage', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Press Link',
                'verbose_name_plural': 'Press Links',
                'ordering': ['-first_published_at'],
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.AlterField(
            model_name='sectionpage',
            name='body',
            field=wagtail.core.fields.StreamField([('areas_of_focus_block', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Leave empty to use default: "Areas of Focus"', required=False)), ('tags', wagtail.core.blocks.ListBlock(wagtail.snippets.blocks.SnippetChooserBlock('taxonomy.FocusAreaTag', required=True), label='Areas of Focus', max_num=3, min_num=1))])), ('sectors_block', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Leave empty to use default: "Sectors"', required=False)), ('tags', wagtail.core.blocks.ListBlock(wagtail.snippets.blocks.SnippetChooserBlock('taxonomy.SectorTag', required=True), label='Sectors', max_num=3, min_num=1))])), ('latest_section_content', wagtail.core.blocks.StructBlock([('section_page', wagtail.core.blocks.PageChooserBlock(label='Front page of section', page_type=['content.SectionPage'], required=True))])), ('publication_types', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Leave empty to use default: "View by publication type"', required=False)), ('types', wagtail.core.blocks.MultipleChoiceBlock(choices=modules.content.blocks.stream.get_publication_type_choices))])), ('press_links', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Leave empty to use default: "Press links"', required=False)), ('limit_number', wagtail.core.blocks.IntegerBlock(default=3, required=True))]))], blank=True),
        ),
        migrations.CreateModel(
            name='PressLinkAuthorRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='press_links', to='content.author')),
                ('snippet', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_relationships', to='content.presslink')),
            ],
            options={
                'verbose_name': 'Press link author',
                'verbose_name_plural': 'Press link authors',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
