# Generated by Django 3.2.12 on 2022-03-01 12:32

from django.db import migrations
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0007_auto_20220301_1143'),
        ('notion', '0004_alter_countrytag_body'),
        ('content', '0038_auto_20220301_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamprofilepage',
            name='areas_of_focus',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taxonomy.FocusAreaTaggedPage', to='taxonomy.FocusAreaTag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='teamprofilepage',
            name='countries',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='notion.CountryTaggedPage', to='notion.CountryTag', verbose_name='Tags'),
        ),
    ]
