# Generated by Django 3.2.12 on 2022-03-01 14:35

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0040_auto_20220301_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='highlight_pages',
            field=wagtail.core.fields.StreamField([('highlight_pages', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='e.g. “Examples of our work”, or leave empty', required=False)), ('pages', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('page', wagtail.core.blocks.PageChooserBlock(required=True)), ('card_format', wagtail.core.blocks.ChoiceBlock(choices=[('default', 'Default')]))]), min_num=1))]))], blank=True),
        ),
    ]
