# Generated by Django 3.2.12 on 2022-03-01 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0041_articlepage_highlight_pages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sectionpage',
            options={'verbose_name': 'Section (Impact, etc.)'},
        ),
    ]
