# Generated by Django 3.2.12 on 2022-03-03 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0048_latestsectioncontentpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxonomypage',
            name='taxonomy',
        ),
    ]
