# Generated by Django 3.2.12 on 2022-03-03 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0046_mappage'),
        ('content', '0050_presslinkspage'),
    ]

    operations = [
    ]
