# Generated by Django 3.2.12 on 2022-03-04 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0052_auto_20220304_1123'),
        ('content', '0052_auto_20220304_1234'),
    ]

    operations = [
    ]
