# Generated by Django 3.2.12 on 2022-03-11 11:07

from django.db import migrations, models
import django.db.models.deletion
import modules.content.blocks.stream
import wagtail.blocks
import wagtail.fields
import wagtail.snippets.blocks
import wagtailmodelchooser.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0012_principletag_principletaggedpage'),
        ('content', '0056_auto_20220311_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagpage',
            name='principle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tagpages', to='taxonomy.principletag'),
        ),
        migrations.AddField(
            model_name='tagpage',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tagpages', to='taxonomy.sectiontag'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='additional_content',
            field=wagtail.fields.StreamField([('similar_content', wagtail.blocks.StructBlock([('suggest_by', wagtail.blocks.ChoiceBlock(choices=[('sector', 'Sector'), ('publication_type', 'Publication Type'), ('author', 'Author'), ('country', 'Country'), ('section', 'Section'), ('principles', 'Open Ownership Principles')]))])), ('highlight_pages', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='e.g. “Examples of our work”, or leave empty', required=False)), ('pages', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(required=True)), ('card_format', wagtail.blocks.ChoiceBlock(choices=[('landscape', 'Landscape'), ('portrait', 'Portrait')]))]), min_num=1))]))], blank=True),
        ),
        migrations.AlterField(
            model_name='blogarticlepage',
            name='additional_content',
            field=wagtail.fields.StreamField([('similar_content', wagtail.blocks.StructBlock([('suggest_by', wagtail.blocks.ChoiceBlock(choices=[('sector', 'Sector'), ('publication_type', 'Publication Type'), ('author', 'Author'), ('country', 'Country'), ('section', 'Section'), ('principles', 'Open Ownership Principles')]))])), ('highlight_pages', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='e.g. “Examples of our work”, or leave empty', required=False)), ('pages', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(required=True)), ('card_format', wagtail.blocks.ChoiceBlock(choices=[('landscape', 'Landscape'), ('portrait', 'Portrait')]))]), min_num=1))]))], blank=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('highlight_pages', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='e.g. “Examples of our work”, or leave empty', required=False)), ('pages', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(required=True)), ('card_format', wagtail.blocks.ChoiceBlock(choices=[('landscape', 'Landscape'), ('portrait', 'Portrait')]))]), min_num=1))])), ('latest_section_content', wagtail.blocks.StructBlock([('section_page', wagtail.blocks.PageChooserBlock(label='Front page of section', page_type=['content.SectionPage'], required=True))])), ('latest_by_publication_type', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='If blank, will use "Latest"', required=False)), ('publication_type', wagtailmodelchooser.blocks.ModelChooserBlock(required=True, target_model='taxonomy.publicationtype'))])), ('latest_by_topic', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='If blank, will use "Latest"', required=False)), ('sector', wagtailmodelchooser.blocks.ModelChooserBlock(required=True, target_model='taxonomy.sectortag'))])), ('latest_by_section_tag', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='If blank, will use "Latest"', required=False)), ('section', wagtailmodelchooser.blocks.ModelChooserBlock(required=True, target_model='taxonomy.sectiontag'))])), ('latest_by_open_ownership_principle', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='If blank, will use "Latest"', required=False)), ('principle', wagtailmodelchooser.blocks.ModelChooserBlock(required=True, target_model='taxonomy.principletag'))]))], blank=True),
        ),
        migrations.AlterField(
            model_name='jobpage',
            name='additional_content',
            field=wagtail.fields.StreamField([('similar_content', wagtail.blocks.StructBlock([('suggest_by', wagtail.blocks.ChoiceBlock(choices=[('sector', 'Sector'), ('publication_type', 'Publication Type'), ('author', 'Author'), ('country', 'Country'), ('section', 'Section'), ('principles', 'Open Ownership Principles')]))])), ('highlight_pages', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='e.g. “Examples of our work”, or leave empty', required=False)), ('pages', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(required=True)), ('card_format', wagtail.blocks.ChoiceBlock(choices=[('landscape', 'Landscape'), ('portrait', 'Portrait')]))]), min_num=1))]))], blank=True),
        ),
        migrations.AlterField(
            model_name='newsarticlepage',
            name='additional_content',
            field=wagtail.fields.StreamField([('similar_content', wagtail.blocks.StructBlock([('suggest_by', wagtail.blocks.ChoiceBlock(choices=[('sector', 'Sector'), ('publication_type', 'Publication Type'), ('author', 'Author'), ('country', 'Country'), ('section', 'Section'), ('principles', 'Open Ownership Principles')]))])), ('highlight_pages', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='e.g. “Examples of our work”, or leave empty', required=False)), ('pages', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(required=True)), ('card_format', wagtail.blocks.ChoiceBlock(choices=[('landscape', 'Landscape'), ('portrait', 'Portrait')]))]), min_num=1))]))], blank=True),
        ),
        migrations.AlterField(
            model_name='publicationfrontpage',
            name='additional_content',
            field=wagtail.fields.StreamField([('similar_content', wagtail.blocks.StructBlock([('suggest_by', wagtail.blocks.ChoiceBlock(choices=[('sector', 'Sector'), ('publication_type', 'Publication Type'), ('author', 'Author'), ('country', 'Country'), ('section', 'Section'), ('principles', 'Open Ownership Principles')]))])), ('highlight_pages', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='e.g. “Examples of our work”, or leave empty', required=False)), ('pages', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(required=True)), ('card_format', wagtail.blocks.ChoiceBlock(choices=[('landscape', 'Landscape'), ('portrait', 'Portrait')]))]), min_num=1))]))], blank=True),
        ),
        migrations.AlterField(
            model_name='publicationinnerpage',
            name='additional_content',
            field=wagtail.fields.StreamField([('similar_content', wagtail.blocks.StructBlock([('suggest_by', wagtail.blocks.ChoiceBlock(choices=[('sector', 'Sector'), ('publication_type', 'Publication Type'), ('author', 'Author'), ('country', 'Country'), ('section', 'Section'), ('principles', 'Open Ownership Principles')]))])), ('highlight_pages', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='e.g. “Examples of our work”, or leave empty', required=False)), ('pages', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(required=True)), ('card_format', wagtail.blocks.ChoiceBlock(choices=[('landscape', 'Landscape'), ('portrait', 'Portrait')]))]), min_num=1))]))], blank=True),
        ),
        migrations.AlterField(
            model_name='sectionpage',
            name='body',
            field=wagtail.fields.StreamField([('highlight_pages', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='e.g. “Examples of our work”, or leave empty', required=False)), ('pages', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(required=True)), ('card_format', wagtail.blocks.ChoiceBlock(choices=[('landscape', 'Landscape'), ('portrait', 'Portrait')]))]), min_num=1))])), ('topics_block', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Leave empty to use default: "Sectors"', required=False)), ('card_format', wagtail.blocks.ChoiceBlock(choices=[('landscape', 'Landscape'), ('portrait', 'Portrait')])), ('tags', wagtail.blocks.ListBlock(wagtail.snippets.blocks.SnippetChooserBlock('taxonomy.SectorTag', required=True), label='Sectors', max_num=3, min_num=1))])), ('latest_section_content', wagtail.blocks.StructBlock([('section_page', wagtail.blocks.PageChooserBlock(label='Front page of section', page_type=['content.SectionPage'], required=True))])), ('publication_types', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Leave empty to use default: "View by publication type"', required=False)), ('card_format', wagtail.blocks.ChoiceBlock(choices=[('landscape', 'Landscape'), ('portrait', 'Portrait')])), ('types', wagtail.blocks.MultipleChoiceBlock(choices=modules.content.blocks.stream.get_publication_type_choices))])), ('press_links', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Leave empty to use default: "Press links"', required=False)), ('card_format', wagtail.blocks.ChoiceBlock(choices=[('landscape', 'Landscape'), ('portrait', 'Portrait')])), ('limit_number', wagtail.blocks.IntegerBlock(default=3, required=True))]))], blank=True),
        ),
        migrations.AlterField(
            model_name='utilitypage',
            name='additional_content',
            field=wagtail.fields.StreamField([('similar_content', wagtail.blocks.StructBlock([('suggest_by', wagtail.blocks.ChoiceBlock(choices=[('sector', 'Sector'), ('publication_type', 'Publication Type'), ('author', 'Author'), ('country', 'Country'), ('section', 'Section'), ('principles', 'Open Ownership Principles')]))])), ('highlight_pages', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='e.g. “Examples of our work”, or leave empty', required=False)), ('pages', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(required=True)), ('card_format', wagtail.blocks.ChoiceBlock(choices=[('landscape', 'Landscape'), ('portrait', 'Portrait')]))]), min_num=1))]))], blank=True),
        ),
    ]
