# Generated by Django 3.2.12 on 2022-03-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0057_auto_20220311_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonomypage',
            name='tags_title',
            field=models.CharField(blank=True, help_text='Will appear above the cards linking to each Tag Page', max_length=255),
        ),
    ]
