# Generated by Django 3.2.12 on 2022-03-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0059_auto_20220316_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationfrontpage',
            name='show_display_date',
            field=models.BooleanField(default=True, help_text="Should this date be displayed as the publication's date?", verbose_name='Show Display Date?'),
        ),
    ]
