# Generated by Django 3.2.12 on 2022-03-21 12:19

from django.db import migrations
import modules.content.blocks.stream
import wagtail.blocks
import wagtail.fields
import wagtail.snippets.blocks
import wagtailmodelchooser.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0060_publicationfrontpage_show_display_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='additional_content',
            field=wagtail.fields.StreamField([('similar_content', wagtail.blocks.StructBlock([('suggest_by', wagtail.blocks.ChoiceBlock(choices=[('sector', 'Topic'), ('publication_type', 'Content Type'), ('author', 'Author'), ('country', 'Country'), ('section', 'Section'), ('principles', 'Open Ownership Principles')]))])), ('highlight_pages', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='e.g. “Examples of our work”, or leave empty', required=False)), ('pages', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(required=True)), ('card_format', wagtail.blocks.ChoiceBlock(choices=[('landscape', 'Landscape'), ('portrait', 'Portrait')]))]), min_num=1))]))], blank=True),
        ),
        migrations.AlterField(
            model_name='blogarticlepage',
            name='additional_content',
            field=wagtail.fields.StreamField([('similar_content', wagtail.blocks.StructBlock([('suggest_by', wagtail.blocks.ChoiceBlock(choices=[('sector', 'Topic'), ('publication_type', 'Content Type'), ('author', 'Author'), ('country', 'Country'), ('section', 'Section'), ('principles', 'Open Ownership Principles')]))])), ('highlight_pages', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='e.g. “Examples of our work”, or leave empty', required=False)), ('pages', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(required=True)), ('card_format', wagtail.blocks.ChoiceBlock(choices=[('landscape', 'Landscape'), ('portrait', 'Portrait')]))]), min_num=1))]))], blank=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('highlight_pages', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='e.g. “Examples of our work”, or leave empty', required=False)), ('pages', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(required=True)), ('card_format', wagtail.blocks.ChoiceBlock(choices=[('landscape', 'Landscape'), ('portrait', 'Portrait')]))]), min_num=1))])), ('publication_types', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Leave empty to use default: "View by publication type"', required=False)), ('card_format', wagtail.blocks.ChoiceBlock(choices=[('landscape', 'Landscape'), ('portrait', 'Portrait')])), ('types', wagtail.blocks.MultipleChoiceBlock(choices=modules.content.blocks.stream.get_publication_type_choices))], label='Content types')), ('latest_section_content', wagtail.blocks.StructBlock([('section_page', wagtail.blocks.PageChooserBlock(label='Front page of section', page_type=['content.SectionPage'], required=True))])), ('latest_by_publication_type', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='If blank, will use "Latest"', required=False)), ('publication_type', wagtailmodelchooser.blocks.ModelChooserBlock(required=True, target_model='taxonomy.publicationtype'))], label='Latest by content type')), ('latest_by_topic', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='If blank, will use "Latest"', required=False)), ('sector', wagtailmodelchooser.blocks.ModelChooserBlock(required=True, target_model='taxonomy.sectortag'))])), ('latest_by_section_tag', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='If blank, will use "Latest"', required=False)), ('section', wagtailmodelchooser.blocks.ModelChooserBlock(required=True, target_model='taxonomy.sectiontag'))])), ('latest_by_open_ownership_principle', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='If blank, will use "Latest"', required=False)), ('principle', wagtailmodelchooser.blocks.ModelChooserBlock(required=True, target_model='taxonomy.principletag'))])), ('latest_from_the_blog', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(default='Latest blog posts', required=True)), ('section', wagtailmodelchooser.blocks.ModelChooserBlock(help_text='', required=False, target_model='taxonomy.sectiontag'))])), ('latest_news', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(default='Latest news', required=True)), ('section', wagtailmodelchooser.blocks.ModelChooserBlock(help_text='', required=False, target_model='taxonomy.sectiontag'))])), ('latest_publications', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(default='Latest publications', required=True)), ('section', wagtailmodelchooser.blocks.ModelChooserBlock(help_text='', required=False, target_model='taxonomy.sectiontag'))])), ('latest_content', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(default='Latest', required=True)), ('section', wagtailmodelchooser.blocks.ModelChooserBlock(help_text='', required=False, target_model='taxonomy.sectiontag'))]))], blank=True),
        ),
        migrations.AlterField(
            model_name='jobpage',
            name='additional_content',
            field=wagtail.fields.StreamField([('similar_content', wagtail.blocks.StructBlock([('suggest_by', wagtail.blocks.ChoiceBlock(choices=[('sector', 'Topic'), ('publication_type', 'Content Type'), ('author', 'Author'), ('country', 'Country'), ('section', 'Section'), ('principles', 'Open Ownership Principles')]))])), ('highlight_pages', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='e.g. “Examples of our work”, or leave empty', required=False)), ('pages', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(required=True)), ('card_format', wagtail.blocks.ChoiceBlock(choices=[('landscape', 'Landscape'), ('portrait', 'Portrait')]))]), min_num=1))]))], blank=True),
        ),
        migrations.AlterField(
            model_name='newsarticlepage',
            name='additional_content',
            field=wagtail.fields.StreamField([('similar_content', wagtail.blocks.StructBlock([('suggest_by', wagtail.blocks.ChoiceBlock(choices=[('sector', 'Topic'), ('publication_type', 'Content Type'), ('author', 'Author'), ('country', 'Country'), ('section', 'Section'), ('principles', 'Open Ownership Principles')]))])), ('highlight_pages', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='e.g. “Examples of our work”, or leave empty', required=False)), ('pages', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(required=True)), ('card_format', wagtail.blocks.ChoiceBlock(choices=[('landscape', 'Landscape'), ('portrait', 'Portrait')]))]), min_num=1))]))], blank=True),
        ),
        migrations.AlterField(
            model_name='publicationfrontpage',
            name='additional_content',
            field=wagtail.fields.StreamField([('similar_content', wagtail.blocks.StructBlock([('suggest_by', wagtail.blocks.ChoiceBlock(choices=[('sector', 'Topic'), ('publication_type', 'Content Type'), ('author', 'Author'), ('country', 'Country'), ('section', 'Section'), ('principles', 'Open Ownership Principles')]))])), ('highlight_pages', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='e.g. “Examples of our work”, or leave empty', required=False)), ('pages', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(required=True)), ('card_format', wagtail.blocks.ChoiceBlock(choices=[('landscape', 'Landscape'), ('portrait', 'Portrait')]))]), min_num=1))]))], blank=True),
        ),
        migrations.AlterField(
            model_name='publicationinnerpage',
            name='additional_content',
            field=wagtail.fields.StreamField([('similar_content', wagtail.blocks.StructBlock([('suggest_by', wagtail.blocks.ChoiceBlock(choices=[('sector', 'Topic'), ('publication_type', 'Content Type'), ('author', 'Author'), ('country', 'Country'), ('section', 'Section'), ('principles', 'Open Ownership Principles')]))])), ('highlight_pages', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='e.g. “Examples of our work”, or leave empty', required=False)), ('pages', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(required=True)), ('card_format', wagtail.blocks.ChoiceBlock(choices=[('landscape', 'Landscape'), ('portrait', 'Portrait')]))]), min_num=1))]))], blank=True),
        ),
        migrations.AlterField(
            model_name='sectionpage',
            name='body',
            field=wagtail.fields.StreamField([('highlight_pages', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='e.g. “Examples of our work”, or leave empty', required=False)), ('pages', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(required=True)), ('card_format', wagtail.blocks.ChoiceBlock(choices=[('landscape', 'Landscape'), ('portrait', 'Portrait')]))]), min_num=1))])), ('topics_block', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Leave empty to use default: "Topics"', required=False)), ('card_format', wagtail.blocks.ChoiceBlock(choices=[('landscape', 'Landscape'), ('portrait', 'Portrait')])), ('tags', wagtail.blocks.ListBlock(wagtail.snippets.blocks.SnippetChooserBlock('taxonomy.SectorTag', required=True), label='Topics', max_num=3, min_num=1))], label='Topics')), ('latest_section_content', wagtail.blocks.StructBlock([('section_page', wagtail.blocks.PageChooserBlock(label='Front page of section', page_type=['content.SectionPage'], required=True))])), ('publication_types', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Leave empty to use default: "View by publication type"', required=False)), ('card_format', wagtail.blocks.ChoiceBlock(choices=[('landscape', 'Landscape'), ('portrait', 'Portrait')])), ('types', wagtail.blocks.MultipleChoiceBlock(choices=modules.content.blocks.stream.get_publication_type_choices))], label='Content types')), ('press_links', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Leave empty to use default: "Press links"', required=False)), ('card_format', wagtail.blocks.ChoiceBlock(choices=[('landscape', 'Landscape'), ('portrait', 'Portrait')])), ('limit_number', wagtail.blocks.IntegerBlock(default=3, required=True))])), ('latest_from_the_blog', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(default='Latest blog posts', required=True)), ('section', wagtailmodelchooser.blocks.ModelChooserBlock(help_text='', required=False, target_model='taxonomy.sectiontag'))])), ('latest_news', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(default='Latest news', required=True)), ('section', wagtailmodelchooser.blocks.ModelChooserBlock(help_text='', required=False, target_model='taxonomy.sectiontag'))])), ('latest_publications', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(default='Latest publications', required=True)), ('section', wagtailmodelchooser.blocks.ModelChooserBlock(help_text='', required=False, target_model='taxonomy.sectiontag'))]))], blank=True),
        ),
        migrations.AlterField(
            model_name='utilitypage',
            name='additional_content',
            field=wagtail.fields.StreamField([('similar_content', wagtail.blocks.StructBlock([('suggest_by', wagtail.blocks.ChoiceBlock(choices=[('sector', 'Topic'), ('publication_type', 'Content Type'), ('author', 'Author'), ('country', 'Country'), ('section', 'Section'), ('principles', 'Open Ownership Principles')]))])), ('highlight_pages', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='e.g. “Examples of our work”, or leave empty', required=False)), ('pages', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(required=True)), ('card_format', wagtail.blocks.ChoiceBlock(choices=[('landscape', 'Landscape'), ('portrait', 'Portrait')]))]), min_num=1))]))], blank=True),
        ),
    ]
