# Generated by Django 3.2.12 on 2022-03-24 12:27

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modules.content.blocks.stream
import wagtail.blocks
import wagtail.fields
import wagtail.snippets.blocks
import wagtailmodelchooser.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('taxonomy', '0014_sectiontaggedpresslink'),
        ('content', '0061_auto_20220321_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='presslink',
            name='sections',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taxonomy.SectionTaggedPressLink', to='taxonomy.SectionTag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='presslink',
            name='section_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='sectionpage',
            name='body',
            field=wagtail.fields.StreamField([('highlight_pages', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='e.g. “Examples of our work”, or leave empty', required=False)), ('pages', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(required=True)), ('card_format', wagtail.blocks.ChoiceBlock(choices=[('landscape', 'Landscape'), ('portrait', 'Portrait')]))]), min_num=1))])), ('topics_block', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Leave empty to use default: "Topics"', required=False)), ('card_format', wagtail.blocks.ChoiceBlock(choices=[('landscape', 'Landscape'), ('portrait', 'Portrait')])), ('tags', wagtail.blocks.ListBlock(wagtail.snippets.blocks.SnippetChooserBlock('taxonomy.SectorTag', required=True), label='Topics', max_num=3, min_num=1))], label='Topics')), ('latest_section_content', wagtail.blocks.StructBlock([('section_page', wagtail.blocks.PageChooserBlock(label='Front page of section', page_type=['content.SectionPage'], required=True))])), ('publication_types', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Leave empty to use default: "View by publication type"', required=False)), ('card_format', wagtail.blocks.ChoiceBlock(choices=[('landscape', 'Landscape'), ('portrait', 'Portrait')])), ('types', wagtail.blocks.MultipleChoiceBlock(choices=modules.content.blocks.stream.get_publication_type_choices))], label='Content types')), ('press_links', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Leave empty to use default: "Press links"', required=False)), ('limit_number', wagtail.blocks.IntegerBlock(default=3, required=True))])), ('latest_from_the_blog', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(default='Latest blog posts', required=True)), ('section', wagtailmodelchooser.blocks.ModelChooserBlock(help_text='', required=False, target_model='taxonomy.sectiontag'))])), ('latest_news', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(default='Latest news', required=True)), ('section', wagtailmodelchooser.blocks.ModelChooserBlock(help_text='', required=False, target_model='taxonomy.sectiontag'))])), ('latest_publications', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(default='Latest publications', required=True)), ('section', wagtailmodelchooser.blocks.ModelChooserBlock(help_text='', required=False, target_model='taxonomy.sectiontag'))]))], blank=True),
        ),
    ]
