# Generated by Django 3.2.12 on 2022-06-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0064_publicationfrontpage_external_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationfrontpage',
            name='impact_title',
            field=models.CharField(blank=True, default='Benefit / Impact', max_length=255),
        ),
        migrations.AddField(
            model_name='publicationfrontpage',
            name='outcomes_title',
            field=models.CharField(blank=True, default='Key Learning Outcomes', max_length=255),
        ),
        migrations.AddField(
            model_name='publicationfrontpage',
            name='summary_title',
            field=models.CharField(blank=True, default='Summary', max_length=255),
        ),
    ]
