# Generated by Django 4.1.10 on 2023-08-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0070_alter_publicationinnerpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilitypage',
            name='show_sharing_buttons',
            field=models.BooleanField(default=True, help_text='Should the sharing buttons be displayed?', verbose_name='Show Sharing Buttons?'),
        ),
    ]
