# Generated by Django 4.1.9 on 2023-09-08 14:30

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0071_alter_articlepage_body_alter_blogarticlepage_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurepage',
            name='banner_intro',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
