# Generated by Django 5.2.15 on 2026-06-29 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0073_alter_articlepage_body_alter_blogarticlepage_body_and_more'),
        ('core', '0007_siteimage_description_alter_sitedocument_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Override the canonical URL (for syndicated or duplicate content).'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='The phrase this page should rank for. Used by the SEO analysis.', max_length=255),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='og_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Social share image for this page (overrides the site default).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.siteimage'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='og_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='og_type',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='schema_type',
            field=models.CharField(blank=True, help_text='Override the Schema.org type for this page (e.g. Article, FAQPage).', max_length=64),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='seo_disable_json_ld',
            field=models.BooleanField(default=False, help_text="Don't emit JSON-LD structured data for this page."),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='seo_nofollow',
            field=models.BooleanField(default=False, help_text='Ask search engines not to follow links on this page.'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='seo_noindex',
            field=models.BooleanField(default=False, help_text='Ask search engines not to index this page.'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='seo_sitemap_changefreq',
            field=models.CharField(blank=True, choices=[('always', 'Always'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('never', 'Never')], max_length=16),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='seo_sitemap_priority',
            field=models.FloatField(blank=True, help_text='Sitemap priority for this page, 0.0–1.0.', null=True),
        ),
        migrations.AddField(
            model_name='blogarticlepage',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Override the canonical URL (for syndicated or duplicate content).'),
        ),
        migrations.AddField(
            model_name='blogarticlepage',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='The phrase this page should rank for. Used by the SEO analysis.', max_length=255),
        ),
        migrations.AddField(
            model_name='blogarticlepage',
            name='og_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogarticlepage',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Social share image for this page (overrides the site default).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.siteimage'),
        ),
        migrations.AddField(
            model_name='blogarticlepage',
            name='og_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='blogarticlepage',
            name='og_type',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='blogarticlepage',
            name='schema_type',
            field=models.CharField(blank=True, help_text='Override the Schema.org type for this page (e.g. Article, FAQPage).', max_length=64),
        ),
        migrations.AddField(
            model_name='blogarticlepage',
            name='seo_disable_json_ld',
            field=models.BooleanField(default=False, help_text="Don't emit JSON-LD structured data for this page."),
        ),
        migrations.AddField(
            model_name='blogarticlepage',
            name='seo_nofollow',
            field=models.BooleanField(default=False, help_text='Ask search engines not to follow links on this page.'),
        ),
        migrations.AddField(
            model_name='blogarticlepage',
            name='seo_noindex',
            field=models.BooleanField(default=False, help_text='Ask search engines not to index this page.'),
        ),
        migrations.AddField(
            model_name='blogarticlepage',
            name='seo_sitemap_changefreq',
            field=models.CharField(blank=True, choices=[('always', 'Always'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('never', 'Never')], max_length=16),
        ),
        migrations.AddField(
            model_name='blogarticlepage',
            name='seo_sitemap_priority',
            field=models.FloatField(blank=True, help_text='Sitemap priority for this page, 0.0–1.0.', null=True),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Override the canonical URL (for syndicated or duplicate content).'),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='The phrase this page should rank for. Used by the SEO analysis.', max_length=255),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='og_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Social share image for this page (overrides the site default).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.siteimage'),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='og_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='og_type',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='schema_type',
            field=models.CharField(blank=True, help_text='Override the Schema.org type for this page (e.g. Article, FAQPage).', max_length=64),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='seo_disable_json_ld',
            field=models.BooleanField(default=False, help_text="Don't emit JSON-LD structured data for this page."),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='seo_nofollow',
            field=models.BooleanField(default=False, help_text='Ask search engines not to follow links on this page.'),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='seo_noindex',
            field=models.BooleanField(default=False, help_text='Ask search engines not to index this page.'),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='seo_sitemap_changefreq',
            field=models.CharField(blank=True, choices=[('always', 'Always'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('never', 'Never')], max_length=16),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='seo_sitemap_priority',
            field=models.FloatField(blank=True, help_text='Sitemap priority for this page, 0.0–1.0.', null=True),
        ),
        migrations.AddField(
            model_name='glossarypage',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Override the canonical URL (for syndicated or duplicate content).'),
        ),
        migrations.AddField(
            model_name='glossarypage',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='The phrase this page should rank for. Used by the SEO analysis.', max_length=255),
        ),
        migrations.AddField(
            model_name='glossarypage',
            name='og_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='glossarypage',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Social share image for this page (overrides the site default).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.siteimage'),
        ),
        migrations.AddField(
            model_name='glossarypage',
            name='og_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='glossarypage',
            name='og_type',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='glossarypage',
            name='schema_type',
            field=models.CharField(blank=True, help_text='Override the Schema.org type for this page (e.g. Article, FAQPage).', max_length=64),
        ),
        migrations.AddField(
            model_name='glossarypage',
            name='seo_disable_json_ld',
            field=models.BooleanField(default=False, help_text="Don't emit JSON-LD structured data for this page."),
        ),
        migrations.AddField(
            model_name='glossarypage',
            name='seo_nofollow',
            field=models.BooleanField(default=False, help_text='Ask search engines not to follow links on this page.'),
        ),
        migrations.AddField(
            model_name='glossarypage',
            name='seo_noindex',
            field=models.BooleanField(default=False, help_text='Ask search engines not to index this page.'),
        ),
        migrations.AddField(
            model_name='glossarypage',
            name='seo_sitemap_changefreq',
            field=models.CharField(blank=True, choices=[('always', 'Always'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('never', 'Never')], max_length=16),
        ),
        migrations.AddField(
            model_name='glossarypage',
            name='seo_sitemap_priority',
            field=models.FloatField(blank=True, help_text='Sitemap priority for this page, 0.0–1.0.', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Override the canonical URL (for syndicated or duplicate content).'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='The phrase this page should rank for. Used by the SEO analysis.', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='og_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Social share image for this page (overrides the site default).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.siteimage'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='og_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='og_type',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='homepage',
            name='schema_type',
            field=models.CharField(blank=True, help_text='Override the Schema.org type for this page (e.g. Article, FAQPage).', max_length=64),
        ),
        migrations.AddField(
            model_name='homepage',
            name='seo_disable_json_ld',
            field=models.BooleanField(default=False, help_text="Don't emit JSON-LD structured data for this page."),
        ),
        migrations.AddField(
            model_name='homepage',
            name='seo_nofollow',
            field=models.BooleanField(default=False, help_text='Ask search engines not to follow links on this page.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='seo_noindex',
            field=models.BooleanField(default=False, help_text='Ask search engines not to index this page.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='seo_sitemap_changefreq',
            field=models.CharField(blank=True, choices=[('always', 'Always'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('never', 'Never')], max_length=16),
        ),
        migrations.AddField(
            model_name='homepage',
            name='seo_sitemap_priority',
            field=models.FloatField(blank=True, help_text='Sitemap priority for this page, 0.0–1.0.', null=True),
        ),
        migrations.AddField(
            model_name='jobpage',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Override the canonical URL (for syndicated or duplicate content).'),
        ),
        migrations.AddField(
            model_name='jobpage',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='The phrase this page should rank for. Used by the SEO analysis.', max_length=255),
        ),
        migrations.AddField(
            model_name='jobpage',
            name='og_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobpage',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Social share image for this page (overrides the site default).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.siteimage'),
        ),
        migrations.AddField(
            model_name='jobpage',
            name='og_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='jobpage',
            name='og_type',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='jobpage',
            name='schema_type',
            field=models.CharField(blank=True, help_text='Override the Schema.org type for this page (e.g. Article, FAQPage).', max_length=64),
        ),
        migrations.AddField(
            model_name='jobpage',
            name='seo_disable_json_ld',
            field=models.BooleanField(default=False, help_text="Don't emit JSON-LD structured data for this page."),
        ),
        migrations.AddField(
            model_name='jobpage',
            name='seo_nofollow',
            field=models.BooleanField(default=False, help_text='Ask search engines not to follow links on this page.'),
        ),
        migrations.AddField(
            model_name='jobpage',
            name='seo_noindex',
            field=models.BooleanField(default=False, help_text='Ask search engines not to index this page.'),
        ),
        migrations.AddField(
            model_name='jobpage',
            name='seo_sitemap_changefreq',
            field=models.CharField(blank=True, choices=[('always', 'Always'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('never', 'Never')], max_length=16),
        ),
        migrations.AddField(
            model_name='jobpage',
            name='seo_sitemap_priority',
            field=models.FloatField(blank=True, help_text='Sitemap priority for this page, 0.0–1.0.', null=True),
        ),
        migrations.AddField(
            model_name='jobsindexpage',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Override the canonical URL (for syndicated or duplicate content).'),
        ),
        migrations.AddField(
            model_name='jobsindexpage',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='The phrase this page should rank for. Used by the SEO analysis.', max_length=255),
        ),
        migrations.AddField(
            model_name='jobsindexpage',
            name='og_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobsindexpage',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Social share image for this page (overrides the site default).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.siteimage'),
        ),
        migrations.AddField(
            model_name='jobsindexpage',
            name='og_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='jobsindexpage',
            name='og_type',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='jobsindexpage',
            name='schema_type',
            field=models.CharField(blank=True, help_text='Override the Schema.org type for this page (e.g. Article, FAQPage).', max_length=64),
        ),
        migrations.AddField(
            model_name='jobsindexpage',
            name='seo_disable_json_ld',
            field=models.BooleanField(default=False, help_text="Don't emit JSON-LD structured data for this page."),
        ),
        migrations.AddField(
            model_name='jobsindexpage',
            name='seo_nofollow',
            field=models.BooleanField(default=False, help_text='Ask search engines not to follow links on this page.'),
        ),
        migrations.AddField(
            model_name='jobsindexpage',
            name='seo_noindex',
            field=models.BooleanField(default=False, help_text='Ask search engines not to index this page.'),
        ),
        migrations.AddField(
            model_name='jobsindexpage',
            name='seo_sitemap_changefreq',
            field=models.CharField(blank=True, choices=[('always', 'Always'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('never', 'Never')], max_length=16),
        ),
        migrations.AddField(
            model_name='jobsindexpage',
            name='seo_sitemap_priority',
            field=models.FloatField(blank=True, help_text='Sitemap priority for this page, 0.0–1.0.', null=True),
        ),
        migrations.AddField(
            model_name='latestsectioncontentpage',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Override the canonical URL (for syndicated or duplicate content).'),
        ),
        migrations.AddField(
            model_name='latestsectioncontentpage',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='The phrase this page should rank for. Used by the SEO analysis.', max_length=255),
        ),
        migrations.AddField(
            model_name='latestsectioncontentpage',
            name='og_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='latestsectioncontentpage',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Social share image for this page (overrides the site default).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.siteimage'),
        ),
        migrations.AddField(
            model_name='latestsectioncontentpage',
            name='og_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='latestsectioncontentpage',
            name='og_type',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='latestsectioncontentpage',
            name='schema_type',
            field=models.CharField(blank=True, help_text='Override the Schema.org type for this page (e.g. Article, FAQPage).', max_length=64),
        ),
        migrations.AddField(
            model_name='latestsectioncontentpage',
            name='seo_disable_json_ld',
            field=models.BooleanField(default=False, help_text="Don't emit JSON-LD structured data for this page."),
        ),
        migrations.AddField(
            model_name='latestsectioncontentpage',
            name='seo_nofollow',
            field=models.BooleanField(default=False, help_text='Ask search engines not to follow links on this page.'),
        ),
        migrations.AddField(
            model_name='latestsectioncontentpage',
            name='seo_noindex',
            field=models.BooleanField(default=False, help_text='Ask search engines not to index this page.'),
        ),
        migrations.AddField(
            model_name='latestsectioncontentpage',
            name='seo_sitemap_changefreq',
            field=models.CharField(blank=True, choices=[('always', 'Always'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('never', 'Never')], max_length=16),
        ),
        migrations.AddField(
            model_name='latestsectioncontentpage',
            name='seo_sitemap_priority',
            field=models.FloatField(blank=True, help_text='Sitemap priority for this page, 0.0–1.0.', null=True),
        ),
        migrations.AddField(
            model_name='mappage',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Override the canonical URL (for syndicated or duplicate content).'),
        ),
        migrations.AddField(
            model_name='mappage',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='The phrase this page should rank for. Used by the SEO analysis.', max_length=255),
        ),
        migrations.AddField(
            model_name='mappage',
            name='og_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mappage',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Social share image for this page (overrides the site default).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.siteimage'),
        ),
        migrations.AddField(
            model_name='mappage',
            name='og_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mappage',
            name='og_type',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='mappage',
            name='schema_type',
            field=models.CharField(blank=True, help_text='Override the Schema.org type for this page (e.g. Article, FAQPage).', max_length=64),
        ),
        migrations.AddField(
            model_name='mappage',
            name='seo_disable_json_ld',
            field=models.BooleanField(default=False, help_text="Don't emit JSON-LD structured data for this page."),
        ),
        migrations.AddField(
            model_name='mappage',
            name='seo_nofollow',
            field=models.BooleanField(default=False, help_text='Ask search engines not to follow links on this page.'),
        ),
        migrations.AddField(
            model_name='mappage',
            name='seo_noindex',
            field=models.BooleanField(default=False, help_text='Ask search engines not to index this page.'),
        ),
        migrations.AddField(
            model_name='mappage',
            name='seo_sitemap_changefreq',
            field=models.CharField(blank=True, choices=[('always', 'Always'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('never', 'Never')], max_length=16),
        ),
        migrations.AddField(
            model_name='mappage',
            name='seo_sitemap_priority',
            field=models.FloatField(blank=True, help_text='Sitemap priority for this page, 0.0–1.0.', null=True),
        ),
        migrations.AddField(
            model_name='newsarticlepage',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Override the canonical URL (for syndicated or duplicate content).'),
        ),
        migrations.AddField(
            model_name='newsarticlepage',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='The phrase this page should rank for. Used by the SEO analysis.', max_length=255),
        ),
        migrations.AddField(
            model_name='newsarticlepage',
            name='og_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newsarticlepage',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Social share image for this page (overrides the site default).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.siteimage'),
        ),
        migrations.AddField(
            model_name='newsarticlepage',
            name='og_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='newsarticlepage',
            name='og_type',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='newsarticlepage',
            name='schema_type',
            field=models.CharField(blank=True, help_text='Override the Schema.org type for this page (e.g. Article, FAQPage).', max_length=64),
        ),
        migrations.AddField(
            model_name='newsarticlepage',
            name='seo_disable_json_ld',
            field=models.BooleanField(default=False, help_text="Don't emit JSON-LD structured data for this page."),
        ),
        migrations.AddField(
            model_name='newsarticlepage',
            name='seo_nofollow',
            field=models.BooleanField(default=False, help_text='Ask search engines not to follow links on this page.'),
        ),
        migrations.AddField(
            model_name='newsarticlepage',
            name='seo_noindex',
            field=models.BooleanField(default=False, help_text='Ask search engines not to index this page.'),
        ),
        migrations.AddField(
            model_name='newsarticlepage',
            name='seo_sitemap_changefreq',
            field=models.CharField(blank=True, choices=[('always', 'Always'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('never', 'Never')], max_length=16),
        ),
        migrations.AddField(
            model_name='newsarticlepage',
            name='seo_sitemap_priority',
            field=models.FloatField(blank=True, help_text='Sitemap priority for this page, 0.0–1.0.', null=True),
        ),
        migrations.AddField(
            model_name='newsindexpage',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Override the canonical URL (for syndicated or duplicate content).'),
        ),
        migrations.AddField(
            model_name='newsindexpage',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='The phrase this page should rank for. Used by the SEO analysis.', max_length=255),
        ),
        migrations.AddField(
            model_name='newsindexpage',
            name='og_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newsindexpage',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Social share image for this page (overrides the site default).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.siteimage'),
        ),
        migrations.AddField(
            model_name='newsindexpage',
            name='og_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='newsindexpage',
            name='og_type',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='newsindexpage',
            name='schema_type',
            field=models.CharField(blank=True, help_text='Override the Schema.org type for this page (e.g. Article, FAQPage).', max_length=64),
        ),
        migrations.AddField(
            model_name='newsindexpage',
            name='seo_disable_json_ld',
            field=models.BooleanField(default=False, help_text="Don't emit JSON-LD structured data for this page."),
        ),
        migrations.AddField(
            model_name='newsindexpage',
            name='seo_nofollow',
            field=models.BooleanField(default=False, help_text='Ask search engines not to follow links on this page.'),
        ),
        migrations.AddField(
            model_name='newsindexpage',
            name='seo_noindex',
            field=models.BooleanField(default=False, help_text='Ask search engines not to index this page.'),
        ),
        migrations.AddField(
            model_name='newsindexpage',
            name='seo_sitemap_changefreq',
            field=models.CharField(blank=True, choices=[('always', 'Always'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('never', 'Never')], max_length=16),
        ),
        migrations.AddField(
            model_name='newsindexpage',
            name='seo_sitemap_priority',
            field=models.FloatField(blank=True, help_text='Sitemap priority for this page, 0.0–1.0.', null=True),
        ),
        migrations.AddField(
            model_name='presslinkspage',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Override the canonical URL (for syndicated or duplicate content).'),
        ),
        migrations.AddField(
            model_name='presslinkspage',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='The phrase this page should rank for. Used by the SEO analysis.', max_length=255),
        ),
        migrations.AddField(
            model_name='presslinkspage',
            name='og_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='presslinkspage',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Social share image for this page (overrides the site default).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.siteimage'),
        ),
        migrations.AddField(
            model_name='presslinkspage',
            name='og_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='presslinkspage',
            name='og_type',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='presslinkspage',
            name='schema_type',
            field=models.CharField(blank=True, help_text='Override the Schema.org type for this page (e.g. Article, FAQPage).', max_length=64),
        ),
        migrations.AddField(
            model_name='presslinkspage',
            name='seo_disable_json_ld',
            field=models.BooleanField(default=False, help_text="Don't emit JSON-LD structured data for this page."),
        ),
        migrations.AddField(
            model_name='presslinkspage',
            name='seo_nofollow',
            field=models.BooleanField(default=False, help_text='Ask search engines not to follow links on this page.'),
        ),
        migrations.AddField(
            model_name='presslinkspage',
            name='seo_noindex',
            field=models.BooleanField(default=False, help_text='Ask search engines not to index this page.'),
        ),
        migrations.AddField(
            model_name='presslinkspage',
            name='seo_sitemap_changefreq',
            field=models.CharField(blank=True, choices=[('always', 'Always'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('never', 'Never')], max_length=16),
        ),
        migrations.AddField(
            model_name='presslinkspage',
            name='seo_sitemap_priority',
            field=models.FloatField(blank=True, help_text='Sitemap priority for this page, 0.0–1.0.', null=True),
        ),
        migrations.AddField(
            model_name='publicationfrontpage',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Override the canonical URL (for syndicated or duplicate content).'),
        ),
        migrations.AddField(
            model_name='publicationfrontpage',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='The phrase this page should rank for. Used by the SEO analysis.', max_length=255),
        ),
        migrations.AddField(
            model_name='publicationfrontpage',
            name='og_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='publicationfrontpage',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Social share image for this page (overrides the site default).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.siteimage'),
        ),
        migrations.AddField(
            model_name='publicationfrontpage',
            name='og_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='publicationfrontpage',
            name='og_type',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='publicationfrontpage',
            name='schema_type',
            field=models.CharField(blank=True, help_text='Override the Schema.org type for this page (e.g. Article, FAQPage).', max_length=64),
        ),
        migrations.AddField(
            model_name='publicationfrontpage',
            name='seo_disable_json_ld',
            field=models.BooleanField(default=False, help_text="Don't emit JSON-LD structured data for this page."),
        ),
        migrations.AddField(
            model_name='publicationfrontpage',
            name='seo_nofollow',
            field=models.BooleanField(default=False, help_text='Ask search engines not to follow links on this page.'),
        ),
        migrations.AddField(
            model_name='publicationfrontpage',
            name='seo_noindex',
            field=models.BooleanField(default=False, help_text='Ask search engines not to index this page.'),
        ),
        migrations.AddField(
            model_name='publicationfrontpage',
            name='seo_sitemap_changefreq',
            field=models.CharField(blank=True, choices=[('always', 'Always'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('never', 'Never')], max_length=16),
        ),
        migrations.AddField(
            model_name='publicationfrontpage',
            name='seo_sitemap_priority',
            field=models.FloatField(blank=True, help_text='Sitemap priority for this page, 0.0–1.0.', null=True),
        ),
        migrations.AddField(
            model_name='publicationinnerpage',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Override the canonical URL (for syndicated or duplicate content).'),
        ),
        migrations.AddField(
            model_name='publicationinnerpage',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='The phrase this page should rank for. Used by the SEO analysis.', max_length=255),
        ),
        migrations.AddField(
            model_name='publicationinnerpage',
            name='og_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='publicationinnerpage',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Social share image for this page (overrides the site default).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.siteimage'),
        ),
        migrations.AddField(
            model_name='publicationinnerpage',
            name='og_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='publicationinnerpage',
            name='og_type',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='publicationinnerpage',
            name='schema_type',
            field=models.CharField(blank=True, help_text='Override the Schema.org type for this page (e.g. Article, FAQPage).', max_length=64),
        ),
        migrations.AddField(
            model_name='publicationinnerpage',
            name='seo_disable_json_ld',
            field=models.BooleanField(default=False, help_text="Don't emit JSON-LD structured data for this page."),
        ),
        migrations.AddField(
            model_name='publicationinnerpage',
            name='seo_nofollow',
            field=models.BooleanField(default=False, help_text='Ask search engines not to follow links on this page.'),
        ),
        migrations.AddField(
            model_name='publicationinnerpage',
            name='seo_noindex',
            field=models.BooleanField(default=False, help_text='Ask search engines not to index this page.'),
        ),
        migrations.AddField(
            model_name='publicationinnerpage',
            name='seo_sitemap_changefreq',
            field=models.CharField(blank=True, choices=[('always', 'Always'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('never', 'Never')], max_length=16),
        ),
        migrations.AddField(
            model_name='publicationinnerpage',
            name='seo_sitemap_priority',
            field=models.FloatField(blank=True, help_text='Sitemap priority for this page, 0.0–1.0.', null=True),
        ),
        migrations.AddField(
            model_name='publicationsindexpage',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Override the canonical URL (for syndicated or duplicate content).'),
        ),
        migrations.AddField(
            model_name='publicationsindexpage',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='The phrase this page should rank for. Used by the SEO analysis.', max_length=255),
        ),
        migrations.AddField(
            model_name='publicationsindexpage',
            name='og_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='publicationsindexpage',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Social share image for this page (overrides the site default).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.siteimage'),
        ),
        migrations.AddField(
            model_name='publicationsindexpage',
            name='og_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='publicationsindexpage',
            name='og_type',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='publicationsindexpage',
            name='schema_type',
            field=models.CharField(blank=True, help_text='Override the Schema.org type for this page (e.g. Article, FAQPage).', max_length=64),
        ),
        migrations.AddField(
            model_name='publicationsindexpage',
            name='seo_disable_json_ld',
            field=models.BooleanField(default=False, help_text="Don't emit JSON-LD structured data for this page."),
        ),
        migrations.AddField(
            model_name='publicationsindexpage',
            name='seo_nofollow',
            field=models.BooleanField(default=False, help_text='Ask search engines not to follow links on this page.'),
        ),
        migrations.AddField(
            model_name='publicationsindexpage',
            name='seo_noindex',
            field=models.BooleanField(default=False, help_text='Ask search engines not to index this page.'),
        ),
        migrations.AddField(
            model_name='publicationsindexpage',
            name='seo_sitemap_changefreq',
            field=models.CharField(blank=True, choices=[('always', 'Always'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('never', 'Never')], max_length=16),
        ),
        migrations.AddField(
            model_name='publicationsindexpage',
            name='seo_sitemap_priority',
            field=models.FloatField(blank=True, help_text='Sitemap priority for this page, 0.0–1.0.', null=True),
        ),
        migrations.AddField(
            model_name='searchpage',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Override the canonical URL (for syndicated or duplicate content).'),
        ),
        migrations.AddField(
            model_name='searchpage',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='The phrase this page should rank for. Used by the SEO analysis.', max_length=255),
        ),
        migrations.AddField(
            model_name='searchpage',
            name='og_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='searchpage',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Social share image for this page (overrides the site default).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.siteimage'),
        ),
        migrations.AddField(
            model_name='searchpage',
            name='og_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='searchpage',
            name='og_type',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='searchpage',
            name='schema_type',
            field=models.CharField(blank=True, help_text='Override the Schema.org type for this page (e.g. Article, FAQPage).', max_length=64),
        ),
        migrations.AddField(
            model_name='searchpage',
            name='seo_disable_json_ld',
            field=models.BooleanField(default=False, help_text="Don't emit JSON-LD structured data for this page."),
        ),
        migrations.AddField(
            model_name='searchpage',
            name='seo_nofollow',
            field=models.BooleanField(default=False, help_text='Ask search engines not to follow links on this page.'),
        ),
        migrations.AddField(
            model_name='searchpage',
            name='seo_noindex',
            field=models.BooleanField(default=False, help_text='Ask search engines not to index this page.'),
        ),
        migrations.AddField(
            model_name='searchpage',
            name='seo_sitemap_changefreq',
            field=models.CharField(blank=True, choices=[('always', 'Always'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('never', 'Never')], max_length=16),
        ),
        migrations.AddField(
            model_name='searchpage',
            name='seo_sitemap_priority',
            field=models.FloatField(blank=True, help_text='Sitemap priority for this page, 0.0–1.0.', null=True),
        ),
        migrations.AddField(
            model_name='sectionpage',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Override the canonical URL (for syndicated or duplicate content).'),
        ),
        migrations.AddField(
            model_name='sectionpage',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='The phrase this page should rank for. Used by the SEO analysis.', max_length=255),
        ),
        migrations.AddField(
            model_name='sectionpage',
            name='og_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sectionpage',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Social share image for this page (overrides the site default).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.siteimage'),
        ),
        migrations.AddField(
            model_name='sectionpage',
            name='og_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sectionpage',
            name='og_type',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='sectionpage',
            name='schema_type',
            field=models.CharField(blank=True, help_text='Override the Schema.org type for this page (e.g. Article, FAQPage).', max_length=64),
        ),
        migrations.AddField(
            model_name='sectionpage',
            name='seo_disable_json_ld',
            field=models.BooleanField(default=False, help_text="Don't emit JSON-LD structured data for this page."),
        ),
        migrations.AddField(
            model_name='sectionpage',
            name='seo_nofollow',
            field=models.BooleanField(default=False, help_text='Ask search engines not to follow links on this page.'),
        ),
        migrations.AddField(
            model_name='sectionpage',
            name='seo_noindex',
            field=models.BooleanField(default=False, help_text='Ask search engines not to index this page.'),
        ),
        migrations.AddField(
            model_name='sectionpage',
            name='seo_sitemap_changefreq',
            field=models.CharField(blank=True, choices=[('always', 'Always'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('never', 'Never')], max_length=16),
        ),
        migrations.AddField(
            model_name='sectionpage',
            name='seo_sitemap_priority',
            field=models.FloatField(blank=True, help_text='Sitemap priority for this page, 0.0–1.0.', null=True),
        ),
        migrations.AddField(
            model_name='tagpage',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Override the canonical URL (for syndicated or duplicate content).'),
        ),
        migrations.AddField(
            model_name='tagpage',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='The phrase this page should rank for. Used by the SEO analysis.', max_length=255),
        ),
        migrations.AddField(
            model_name='tagpage',
            name='og_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tagpage',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Social share image for this page (overrides the site default).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.siteimage'),
        ),
        migrations.AddField(
            model_name='tagpage',
            name='og_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tagpage',
            name='og_type',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='tagpage',
            name='schema_type',
            field=models.CharField(blank=True, help_text='Override the Schema.org type for this page (e.g. Article, FAQPage).', max_length=64),
        ),
        migrations.AddField(
            model_name='tagpage',
            name='seo_disable_json_ld',
            field=models.BooleanField(default=False, help_text="Don't emit JSON-LD structured data for this page."),
        ),
        migrations.AddField(
            model_name='tagpage',
            name='seo_nofollow',
            field=models.BooleanField(default=False, help_text='Ask search engines not to follow links on this page.'),
        ),
        migrations.AddField(
            model_name='tagpage',
            name='seo_noindex',
            field=models.BooleanField(default=False, help_text='Ask search engines not to index this page.'),
        ),
        migrations.AddField(
            model_name='tagpage',
            name='seo_sitemap_changefreq',
            field=models.CharField(blank=True, choices=[('always', 'Always'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('never', 'Never')], max_length=16),
        ),
        migrations.AddField(
            model_name='tagpage',
            name='seo_sitemap_priority',
            field=models.FloatField(blank=True, help_text='Sitemap priority for this page, 0.0–1.0.', null=True),
        ),
        migrations.AddField(
            model_name='taxonomypage',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Override the canonical URL (for syndicated or duplicate content).'),
        ),
        migrations.AddField(
            model_name='taxonomypage',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='The phrase this page should rank for. Used by the SEO analysis.', max_length=255),
        ),
        migrations.AddField(
            model_name='taxonomypage',
            name='og_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='taxonomypage',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Social share image for this page (overrides the site default).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.siteimage'),
        ),
        migrations.AddField(
            model_name='taxonomypage',
            name='og_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='taxonomypage',
            name='og_type',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='taxonomypage',
            name='schema_type',
            field=models.CharField(blank=True, help_text='Override the Schema.org type for this page (e.g. Article, FAQPage).', max_length=64),
        ),
        migrations.AddField(
            model_name='taxonomypage',
            name='seo_disable_json_ld',
            field=models.BooleanField(default=False, help_text="Don't emit JSON-LD structured data for this page."),
        ),
        migrations.AddField(
            model_name='taxonomypage',
            name='seo_nofollow',
            field=models.BooleanField(default=False, help_text='Ask search engines not to follow links on this page.'),
        ),
        migrations.AddField(
            model_name='taxonomypage',
            name='seo_noindex',
            field=models.BooleanField(default=False, help_text='Ask search engines not to index this page.'),
        ),
        migrations.AddField(
            model_name='taxonomypage',
            name='seo_sitemap_changefreq',
            field=models.CharField(blank=True, choices=[('always', 'Always'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('never', 'Never')], max_length=16),
        ),
        migrations.AddField(
            model_name='taxonomypage',
            name='seo_sitemap_priority',
            field=models.FloatField(blank=True, help_text='Sitemap priority for this page, 0.0–1.0.', null=True),
        ),
        migrations.AddField(
            model_name='teampage',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Override the canonical URL (for syndicated or duplicate content).'),
        ),
        migrations.AddField(
            model_name='teampage',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='The phrase this page should rank for. Used by the SEO analysis.', max_length=255),
        ),
        migrations.AddField(
            model_name='teampage',
            name='og_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teampage',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Social share image for this page (overrides the site default).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.siteimage'),
        ),
        migrations.AddField(
            model_name='teampage',
            name='og_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='teampage',
            name='og_type',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='teampage',
            name='schema_type',
            field=models.CharField(blank=True, help_text='Override the Schema.org type for this page (e.g. Article, FAQPage).', max_length=64),
        ),
        migrations.AddField(
            model_name='teampage',
            name='seo_disable_json_ld',
            field=models.BooleanField(default=False, help_text="Don't emit JSON-LD structured data for this page."),
        ),
        migrations.AddField(
            model_name='teampage',
            name='seo_nofollow',
            field=models.BooleanField(default=False, help_text='Ask search engines not to follow links on this page.'),
        ),
        migrations.AddField(
            model_name='teampage',
            name='seo_noindex',
            field=models.BooleanField(default=False, help_text='Ask search engines not to index this page.'),
        ),
        migrations.AddField(
            model_name='teampage',
            name='seo_sitemap_changefreq',
            field=models.CharField(blank=True, choices=[('always', 'Always'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('never', 'Never')], max_length=16),
        ),
        migrations.AddField(
            model_name='teampage',
            name='seo_sitemap_priority',
            field=models.FloatField(blank=True, help_text='Sitemap priority for this page, 0.0–1.0.', null=True),
        ),
        migrations.AddField(
            model_name='teamprofilepage',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Override the canonical URL (for syndicated or duplicate content).'),
        ),
        migrations.AddField(
            model_name='teamprofilepage',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='The phrase this page should rank for. Used by the SEO analysis.', max_length=255),
        ),
        migrations.AddField(
            model_name='teamprofilepage',
            name='og_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teamprofilepage',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Social share image for this page (overrides the site default).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.siteimage'),
        ),
        migrations.AddField(
            model_name='teamprofilepage',
            name='og_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='teamprofilepage',
            name='og_type',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='teamprofilepage',
            name='schema_type',
            field=models.CharField(blank=True, help_text='Override the Schema.org type for this page (e.g. Article, FAQPage).', max_length=64),
        ),
        migrations.AddField(
            model_name='teamprofilepage',
            name='seo_disable_json_ld',
            field=models.BooleanField(default=False, help_text="Don't emit JSON-LD structured data for this page."),
        ),
        migrations.AddField(
            model_name='teamprofilepage',
            name='seo_nofollow',
            field=models.BooleanField(default=False, help_text='Ask search engines not to follow links on this page.'),
        ),
        migrations.AddField(
            model_name='teamprofilepage',
            name='seo_noindex',
            field=models.BooleanField(default=False, help_text='Ask search engines not to index this page.'),
        ),
        migrations.AddField(
            model_name='teamprofilepage',
            name='seo_sitemap_changefreq',
            field=models.CharField(blank=True, choices=[('always', 'Always'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('never', 'Never')], max_length=16),
        ),
        migrations.AddField(
            model_name='teamprofilepage',
            name='seo_sitemap_priority',
            field=models.FloatField(blank=True, help_text='Sitemap priority for this page, 0.0–1.0.', null=True),
        ),
        migrations.AddField(
            model_name='themepage',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Override the canonical URL (for syndicated or duplicate content).'),
        ),
        migrations.AddField(
            model_name='themepage',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='The phrase this page should rank for. Used by the SEO analysis.', max_length=255),
        ),
        migrations.AddField(
            model_name='themepage',
            name='og_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='themepage',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Social share image for this page (overrides the site default).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.siteimage'),
        ),
        migrations.AddField(
            model_name='themepage',
            name='og_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='themepage',
            name='og_type',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='themepage',
            name='schema_type',
            field=models.CharField(blank=True, help_text='Override the Schema.org type for this page (e.g. Article, FAQPage).', max_length=64),
        ),
        migrations.AddField(
            model_name='themepage',
            name='seo_disable_json_ld',
            field=models.BooleanField(default=False, help_text="Don't emit JSON-LD structured data for this page."),
        ),
        migrations.AddField(
            model_name='themepage',
            name='seo_nofollow',
            field=models.BooleanField(default=False, help_text='Ask search engines not to follow links on this page.'),
        ),
        migrations.AddField(
            model_name='themepage',
            name='seo_noindex',
            field=models.BooleanField(default=False, help_text='Ask search engines not to index this page.'),
        ),
        migrations.AddField(
            model_name='themepage',
            name='seo_sitemap_changefreq',
            field=models.CharField(blank=True, choices=[('always', 'Always'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('never', 'Never')], max_length=16),
        ),
        migrations.AddField(
            model_name='themepage',
            name='seo_sitemap_priority',
            field=models.FloatField(blank=True, help_text='Sitemap priority for this page, 0.0–1.0.', null=True),
        ),
        migrations.AddField(
            model_name='utilitypage',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Override the canonical URL (for syndicated or duplicate content).'),
        ),
        migrations.AddField(
            model_name='utilitypage',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='The phrase this page should rank for. Used by the SEO analysis.', max_length=255),
        ),
        migrations.AddField(
            model_name='utilitypage',
            name='og_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='utilitypage',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Social share image for this page (overrides the site default).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.siteimage'),
        ),
        migrations.AddField(
            model_name='utilitypage',
            name='og_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='utilitypage',
            name='og_type',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='utilitypage',
            name='schema_type',
            field=models.CharField(blank=True, help_text='Override the Schema.org type for this page (e.g. Article, FAQPage).', max_length=64),
        ),
        migrations.AddField(
            model_name='utilitypage',
            name='seo_disable_json_ld',
            field=models.BooleanField(default=False, help_text="Don't emit JSON-LD structured data for this page."),
        ),
        migrations.AddField(
            model_name='utilitypage',
            name='seo_nofollow',
            field=models.BooleanField(default=False, help_text='Ask search engines not to follow links on this page.'),
        ),
        migrations.AddField(
            model_name='utilitypage',
            name='seo_noindex',
            field=models.BooleanField(default=False, help_text='Ask search engines not to index this page.'),
        ),
        migrations.AddField(
            model_name='utilitypage',
            name='seo_sitemap_changefreq',
            field=models.CharField(blank=True, choices=[('always', 'Always'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('never', 'Never')], max_length=16),
        ),
        migrations.AddField(
            model_name='utilitypage',
            name='seo_sitemap_priority',
            field=models.FloatField(blank=True, help_text='Sitemap priority for this page, 0.0–1.0.', null=True),
        ),
    ]
