# Generated by Django 5.2.15 on 2026-08-11 09:54

import django.db.models.deletion
import wagtail.fields
import wagtailcache.cache
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0074_articlepage_canonical_url_articlepage_focus_keyword_and_more'),
        ('core', '0007_siteimage_description_alter_sitedocument_file_size'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchpage',
            name='suggested_searches_title',
            field=models.CharField(default='People commonly search for', max_length=255),
        ),
        migrations.CreateModel(
            name='BotCentrePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('canonical_url', models.URLField(blank=True, help_text='Override the canonical URL (for syndicated or duplicate content).')),
                ('seo_noindex', models.BooleanField(default=False, help_text='Ask search engines not to index this page.')),
                ('seo_nofollow', models.BooleanField(default=False, help_text='Ask search engines not to follow links on this page.')),
                ('og_title', models.CharField(blank=True, max_length=255)),
                ('og_description', models.TextField(blank=True)),
                ('og_type', models.CharField(blank=True, max_length=64)),
                ('focus_keyword', models.CharField(blank=True, help_text='The phrase this page should rank for. Used by the SEO analysis.', max_length=255)),
                ('seo_sitemap_priority', models.FloatField(blank=True, help_text='Sitemap priority for this page, 0.0–1.0.', null=True)),
                ('seo_sitemap_changefreq', models.CharField(blank=True, choices=[('always', 'Always'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('never', 'Never')], max_length=16)),
                ('schema_type', models.CharField(blank=True, help_text='Override the Schema.org type for this page (e.g. Article, FAQPage).', max_length=64)),
                ('seo_disable_json_ld', models.BooleanField(default=False, help_text="Don't emit JSON-LD structured data for this page.")),
                ('blurb', models.TextField(blank=True, null=True)),
                ('display_date', models.DateField(blank=True, help_text='If blank, this will be set to the date the page was first published', null=True)),
                ('intro', wagtail.fields.RichTextField(blank=True, null=True)),
                ('og_image', models.ForeignKey(blank=True, help_text='Social share image for this page (overrides the site default).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.siteimage')),
                ('thumbnail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.siteimage')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtailcache.cache.WagtailCacheMixin, 'wagtailcore.page', models.Model),
        ),
    ]
