# Generated by Django 5.2.15 on 2026-08-13 14:39

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0075_alter_searchpage_suggested_searches_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botcentrepage',
            name='after_listing',
            field=wagtail.fields.StreamField([('similar_content', 1), ('highlight_pages', 8)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('sector', 'Topic'), ('publication_type', 'Content Type'), ('author', 'Author'), ('country', 'Country'), ('section', 'Section'), ('principles', 'Open Ownership Principles')]}), 1: ('wagtail.blocks.StructBlock', [[('suggest_by', 0)]], {}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. “Examples of our work”, or leave empty', 'required': False}), 3: ('wagtail.blocks.PageChooserBlock', (), {'required': True}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('landscape', 'Landscape'), ('portrait', 'Portrait')]}), 5: ('modules.content.blocks.stream.EmbedBlock', (), {'help_text': "Optional, replaces the page's image. Only appears if Card format is Landscape.", 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('page', 3), ('card_format', 4), ('embed', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {'min_num': 1}), 8: ('wagtail.blocks.StructBlock', [[('title', 2), ('pages', 7)]], {})}),
        ),
        migrations.AddField(
            model_name='botcentrepage',
            name='before_listing',
            field=wagtail.fields.StreamField([('embed', 0), ('rich_text', 1)], blank=True, block_lookup={0: ('modules.content.blocks.stream.EmbedBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'h4', 'h5', 'h6', 'bold', 'italic', 'small', 'ol', 'ul', 'link', 'document-link']})}),
        ),
    ]
