# Generated by Django 5.2.15 on 2026-08-20 17:33

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0076_botcentrepage_after_listing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botcentrepage',
            name='after_listing',
            field=wagtail.fields.StreamField([('embed', 0), ('rich_text', 1), ('expanding_rich_text', 3)], blank=True, block_lookup={0: ('modules.content.blocks.stream.EmbedBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'h4', 'h5', 'h6', 'bold', 'italic', 'small', 'ol', 'ul', 'link', 'document-link']}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'small', 'link', 'document-link'], 'required': True}), 3: ('wagtail.blocks.StructBlock', [[('intro', 2), ('extra', 2)]], {})}),
        ),
        migrations.AlterField(
            model_name='botcentrepage',
            name='before_listing',
            field=wagtail.fields.StreamField([('embed', 0), ('rich_text', 1), ('expanding_rich_text', 3)], blank=True, block_lookup={0: ('modules.content.blocks.stream.EmbedBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'h4', 'h5', 'h6', 'bold', 'italic', 'small', 'ol', 'ul', 'link', 'document-link']}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'small', 'link', 'document-link'], 'required': True}), 3: ('wagtail.blocks.StructBlock', [[('intro', 2), ('extra', 2)]], {})}),
        ),
    ]
