[tool.poetry]
name = "TEMPLATEPROJECT_SHORT_NAME"
version = "0.1.0"
description = "TEMPLATEPROJECT_FULL_NAME"
authors = ["systems@hactar.is"]


[tool.poetry.dependencies]
python = ">=3.8,<3.9"
boto = "*"
boto3 = "*"
bugsnag = "*"
click = "*"
consoler = "*"
django-cacheops = "*"
django-extensions = "*"
django-redis = "*"
django-storages = "*"
django_select2 = "*"
envkey = "*"
hiredis = "*"
ipython = "*"
jinja2 = "*"
loguru = "*"
psycopg2 = "*"
toml = "*"
wagtail = "*"
wagtail-autocomplete = "*"
wagtail-cache = "*"
wagtailfontawesome = "*"
whitenoise = "*"


[tool.poetry.dev-dependencies]
# Django Dev Panel has an incompatibility with Wagtail-Cache, this is "fixed" in my fork, so we're installing from there until my PR gets merged.
django-developer-panel = {git = "https://github.com/drcongo/django-developer-panel.git", rev="55a6721e3df846a97f829a19374103037ba1cb29"}
coverage = "*"
pytest = "*"
pytest-cov = "*"
pytest-django = "*"
pytest-pythonpath = "*"
pytest-sugar = "*"


[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
