[tool.poetry]
name = "openownership.org"
version = "0.1.0"
description = "openownership.org"
authors = ["systems@hactar.is"]


[tool.poetry.dependencies]
python = ">=3.8,<3.10"
boto = "*"
boto3 = "*"
bugsnag = "*"
click = "*"
consoler = "*"
django-cacheops = "*"
django-extensions = "*"
django-redis = "*"
django-storages = "*"
django_select2 = "*"
envkey = "*"
hiredis = "*"
ipython = "8.0.1"
jinja2 = "*"
loguru = "*"
psycopg2-binary = "*"
toml = "*"
wagtail = "^2.16.1"
wagtail-autocomplete = "^0.7.0"
wagtail-cache = "*"
wagtailfontawesome = "*"
whitenoise = "*"
ipdb = "^0.13.9"
wagtail-font-awesome-svg = "^0.0.2"
wagtail-localize = "^1.3"
notion-client = "^0.9.0"
django-cron = "^0.5.1"
jedi = "0.17.2"
wagtail-modelchooser = "^2.13.1"


[tool.poetry.dev-dependencies]
# Django Dev Panel has an incompatibility with Wagtail-Cache, this is "fixed" in my fork, so we're installing from there until my PR gets merged.
django-developer-panel = {git = "https://github.com/drcongo/django-developer-panel.git", rev="55a6721e3df846a97f829a19374103037ba1cb29"}
coverage = "*"
pytest = "*"
pytest-cov = "*"
pytest-django = "*"
pytest-pythonpath = "*"
pytest-sugar = "*"
packaging = "20.4"
codacy-coverage = "^1.3.11"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
