#!/bin/sh
header () {
   echo "\033[46m\033[30m" $1 '\e[?0c \e[0m'
   printf '\e[0m'
   echo "> "
}


echo "Post Receive Hook is running..." >> /var/log/git.log

# Check out the working tree to the right place
header "Checking out git repo"
mkdir -p /srv/www/TEMPLATEPROJECT_SHORT_NAME/
git --work-tree=/srv/www/TEMPLATEPROJECT_SHORT_NAME/ --git-dir=/srv/repos/TEMPLATEPROJECT_SHORT_NAME.git checkout main -f

header "Ensuring various files exist"
# Make sure we have a log file
mkdir -p /var/log/TEMPLATEPROJECT_SHORT_NAME
touch /var/log/TEMPLATEPROJECT_SHORT_NAME/output.log
chown -R deploy:deploy /var/log/TEMPLATEPROJECT_SHORT_NAME


header "Clearing pyc files"
find /srv/www -name "*.pyc" -type f -delete
find /srv/www -name "__pycache__" -type d -ls -exec rm -rv {} +

# Remove files we don't want on the remote server
header "Removing unwanted files and folders"
rm -rf /srv/www/TEMPLATEPROJECT_SHORT_NAME/ansible.cfg \
    /srv/www/TEMPLATEPROJECT_SHORT_NAME/.codacy.yaml \
    /srv/www/TEMPLATEPROJECT_SHORT_NAME/config.toml \
    /srv/www/TEMPLATEPROJECT_SHORT_NAME/_data \
    /srv/www/TEMPLATEPROJECT_SHORT_NAME/_db \
    /srv/www/TEMPLATEPROJECT_SHORT_NAME/devops \
    /srv/www/TEMPLATEPROJECT_SHORT_NAME/docker \
    /srv/www/TEMPLATEPROJECT_SHORT_NAME/docker-compose.test.yml \
    /srv/www/TEMPLATEPROJECT_SHORT_NAME/docker-compose.yml \
    /srv/www/TEMPLATEPROJECT_SHORT_NAME/.dockerignore \
    /srv/www/TEMPLATEPROJECT_SHORT_NAME/fabfile \
    /srv/www/TEMPLATEPROJECT_SHORT_NAME/.github \
    /srv/www/TEMPLATEPROJECT_SHORT_NAME/.gitignore \
    /srv/www/TEMPLATEPROJECT_SHORT_NAME/.gitmodules \
    /srv/www/TEMPLATEPROJECT_SHORT_NAME/README.md \
    /srv/www/TEMPLATEPROJECT_SHORT_NAME/setup.cfg \
    /srv/www/TEMPLATEPROJECT_SHORT_NAME/app/_db

# Ensure envkey is set
header "Setting envkey"
echo 'ENVKEY='$ENVKEY > /srv/www/TEMPLATEPROJECT_SHORT_NAME/app/.env
chown deploy:deploy /srv/www/TEMPLATEPROJECT_SHORT_NAME/app/.env
export SERVER_ENV=production

header "Running poetry install"
cd /srv/www/TEMPLATEPROJECT_SHORT_NAME/app && poetry install --no-dev  --no-root

header "Running migrations"
/srv/www/TEMPLATEPROJECT_SHORT_NAME/app/.venv/bin/python manage.py migrate

header "Collecting static"
/srv/www/TEMPLATEPROJECT_SHORT_NAME/app/.venv/bin/python /srv/www/TEMPLATEPROJECT_SHORT_NAME/app/manage.py collectstatic --no-input

header "Clearing cache"
/srv/www/TEMPLATEPROJECT_SHORT_NAME/app/.venv/bin/python /srv/www/TEMPLATEPROJECT_SHORT_NAME/app/manage.py clear_wagtail_cache

# Restart supervisor apps
header "Restarting the supervisor app"
supervisorctl restart all


header "**************** DONE ****************"
