#!/bin/sh
header () {
   echo "\033[46m\033[30m" $1 '\e[?0c \e[0m'
   printf '\e[0m'
   echo "> "
}


echo "Post Receive Hook is running..." >> /var/log/git.log

# Check out the working tree to the right place
header "Checking out git repo"
mkdir -p /srv/www/
git --work-tree=/srv/www/ --git-dir=/srv/repos/openownership.git checkout main -f

header "Ensuring various files exist"
# Make sure we have a log file
mkdir -p /var/log/openownership.org
touch /var/log/openownership.org/output.log
chown -R deploy:deploy /var/log/openownership.org


header "Clearing pyc files"
find /srv/www -name "*.pyc" -type f -delete
find /srv/www -name "__pycache__" -type d -ls -exec rm -rv {} +

# Remove files we don't want on the remote server
header "Removing unwanted files and folders"
rm -rf /srv/www/ansible.cfg \
    /srv/www/.codacy.yaml \
    /srv/www/config.toml \
    /srv/www/_data \
    /srv/www/_db \
    /srv/www/devops \
    /srv/www/docker \
    /srv/www/docker-compose.test.yml \
    /srv/www/docker-compose.yml \
    /srv/www/.dockerignore \
    /srv/www/fabfile \
    /srv/www/.github \
    /srv/www/.gitignore \
    /srv/www/.gitmodules \
    /srv/www/README.md \
    /srv/www/setup.cfg \
    /srv/www/app/_db

header "Running poetry install"
cd /srv/www/app && poetry install --no-dev  --no-root

header "Running migrations"
/srv/www/app/.venv/bin/python manage.py migrate

header "Collecting static"
/srv/www/app/.venv/bin/python /srv/www/app/manage.py collectstatic --no-input

header "Clearing cache"
/srv/www/app/.venv/bin/python /srv/www/app/manage.py clear_wagtail_cache

# Restart supervisor apps
header "Restarting the supervisor app"
supervisorctl restart all


header "**************** DONE ****************"
