# Generated by Django 3.1.14 on 2022-02-16 16:26

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.documents.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('core', '0003_auto_20220216_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analytics_property_id', models.CharField(blank=True, help_text='Analytics property ID (starting UA-...)', max_length=32, null=True)),
                ('tag_manager_property_id', models.CharField(blank=True, help_text='Tag Manager property ID (starting GTM...)', max_length=32, null=True)),
                ('meta_description', models.TextField(blank=True, help_text='The short description shown in search results (160 characters max)', null=True)),
                ('social_accounts', wagtail.fields.StreamField([('social_links', wagtail.blocks.StructBlock([('service', wagtail.blocks.ChoiceBlock(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn')])), ('url', wagtail.blocks.URLBlock(required=True))]))], blank=True, null=True)),
                ('body', models.CharField(blank=True, max_length=255, null=True)),
                ('link_label', models.CharField(blank=True, default='Find out more', max_length=255, null=True)),
                ('live', models.BooleanField(blank=True, null=True)),
                ('show_on_all_pages', models.BooleanField(blank=True, null=True)),
                ('limit_to_pages', models.ManyToManyField(blank=True, related_name='update_banners', to='wagtailcore.Page')),
                ('link_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailcore.page')),
                ('meta_image', models.ForeignKey(blank=True, help_text='A default image to use when shared on Facebook (aim for 1200x630)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.siteimage')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Site settings',
            },
        ),
        migrations.CreateModel(
            name='NavigationSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navbar_blocks', wagtail.fields.StreamField([('nav_item', wagtail.blocks.StructBlock([('link_type', wagtail.blocks.ChoiceBlock(choices=[('page', 'Page'), ('document', 'Document'), ('url', 'URL')])), ('link_page', wagtail.blocks.PageChooserBlock(label='Linked Page', required=False)), ('link_document', wagtail.documents.blocks.DocumentChooserBlock(label='Linked Document', required=False)), ('link_url', wagtail.blocks.CharBlock(label='URL', required=False)), ('link_label', wagtail.blocks.CharBlock(required=True))])), ('mega_menu', wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock(required=False)), ('objects', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('section_title', wagtail.blocks.CharBlock(required=False)), ('links', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('link_type', wagtail.blocks.ChoiceBlock(choices=[('page', 'Page'), ('document', 'Document'), ('url', 'URL')])), ('link_page', wagtail.blocks.PageChooserBlock(label='Linked Page', required=False)), ('link_document', wagtail.documents.blocks.DocumentChooserBlock(label='Linked Document', required=False)), ('link_url', wagtail.blocks.CharBlock(label='URL', required=False)), ('link_label', wagtail.blocks.CharBlock(required=True))])))])))]))], blank=True, null=True)),
                ('footer_nav', wagtail.fields.StreamField([('nav_item', wagtail.blocks.StructBlock([('link_type', wagtail.blocks.ChoiceBlock(choices=[('page', 'Page'), ('document', 'Document'), ('url', 'URL')])), ('link_page', wagtail.blocks.PageChooserBlock(label='Linked Page', required=False)), ('link_document', wagtail.documents.blocks.DocumentChooserBlock(label='Linked Document', required=False)), ('link_url', wagtail.blocks.CharBlock(label='URL', required=False)), ('link_label', wagtail.blocks.CharBlock(required=True))]))], blank=True, null=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Navigation settings',
            },
        ),
    ]
