# Generated by Django 3.2.12 on 2022-03-02 16:16

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.documents.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_auto_20220216_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationsettings',
            name='navbar_blocks',
            field=wagtail.fields.StreamField([('nav_item', wagtail.blocks.StructBlock([('link_type', wagtail.blocks.ChoiceBlock(choices=[('page', 'Page'), ('document', 'Document'), ('url', 'URL')])), ('link_page', wagtail.blocks.PageChooserBlock(label='Linked Page', required=False)), ('link_document', wagtail.documents.blocks.DocumentChooserBlock(label='Linked Document', required=False)), ('link_url', wagtail.blocks.CharBlock(label='URL', required=False)), ('link_label', wagtail.blocks.CharBlock(required=True))])), ('mega_menu', wagtail.blocks.StructBlock([('nav_item', wagtail.blocks.StructBlock([('link_type', wagtail.blocks.ChoiceBlock(choices=[('page', 'Page'), ('document', 'Document'), ('url', 'URL')])), ('link_page', wagtail.blocks.PageChooserBlock(label='Linked Page', required=False)), ('link_document', wagtail.documents.blocks.DocumentChooserBlock(label='Linked Document', required=False)), ('link_url', wagtail.blocks.CharBlock(label='URL', required=False)), ('link_label', wagtail.blocks.CharBlock(required=True))])), ('objects', wagtail.blocks.StreamBlock([('nav_item', wagtail.blocks.StructBlock([('link_type', wagtail.blocks.ChoiceBlock(choices=[('page', 'Page'), ('document', 'Document'), ('url', 'URL')])), ('link_page', wagtail.blocks.PageChooserBlock(label='Linked Page', required=False)), ('link_document', wagtail.documents.blocks.DocumentChooserBlock(label='Linked Document', required=False)), ('link_url', wagtail.blocks.CharBlock(label='URL', required=False)), ('link_label', wagtail.blocks.CharBlock(required=True))])), ('sub_menu', wagtail.blocks.StructBlock([('nav_item', wagtail.blocks.StructBlock([('link_type', wagtail.blocks.ChoiceBlock(choices=[('page', 'Page'), ('document', 'Document'), ('url', 'URL')])), ('link_page', wagtail.blocks.PageChooserBlock(label='Linked Page', required=False)), ('link_document', wagtail.documents.blocks.DocumentChooserBlock(label='Linked Document', required=False)), ('link_url', wagtail.blocks.CharBlock(label='URL', required=False)), ('link_label', wagtail.blocks.CharBlock(required=True))])), ('links', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('link_type', wagtail.blocks.ChoiceBlock(choices=[('page', 'Page'), ('document', 'Document'), ('url', 'URL')])), ('link_page', wagtail.blocks.PageChooserBlock(label='Linked Page', required=False)), ('link_document', wagtail.documents.blocks.DocumentChooserBlock(label='Linked Document', required=False)), ('link_url', wagtail.blocks.CharBlock(label='URL', required=False)), ('link_label', wagtail.blocks.CharBlock(required=True))])))]))]))]))], blank=True, null=True),
        ),
    ]
