# Generated by Django 3.2.12 on 2022-03-24 10:42

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.documents.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_alter_navigationsettings_navbar_blocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationsettings',
            name='footer_nav2',
            field=wagtail.fields.StreamField([('nav_item', wagtail.blocks.StructBlock([('link_type', wagtail.blocks.ChoiceBlock(choices=[('page', 'Page'), ('document', 'Document'), ('url', 'URL')])), ('link_page', wagtail.blocks.PageChooserBlock(label='Linked Page', required=False)), ('link_document', wagtail.documents.blocks.DocumentChooserBlock(label='Linked Document', required=False)), ('link_url', wagtail.blocks.CharBlock(label='URL', required=False)), ('link_label', wagtail.blocks.CharBlock(required=True))]))], blank=True, null=True),
        ),
    ]
