# Generated by Django 3.2.12 on 2022-06-20 13:54

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtailmodelchooser.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_navigationsettings_footer_nav2'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='body',
            field=wagtail.fields.StreamField([('editors_picks', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(default="Editor's picks", required=False)), ('pages', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(required=True))]), max_num=3, min_num=1))])), ('latest_content', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(default='Latest', required=True)), ('section', wagtailmodelchooser.blocks.ModelChooserBlock(help_text='', required=False, target_model='taxonomy.sectiontag'))]))], blank=True, null=True),
        ),
    ]
